// Diese Datei wurde automatisch am : 25.09.2018 um 15:05:05 generiert und entspricht der Systemversion nach 19.07.2017 10:21:03!!!
// Path: C:\RIEcon36C\Softwarepool\Softwarepool_PES_2018\WPU_2018\WP_1_000_100000\User\Komtabparser.exe

const Pgrup gpr[] = { 
	{"***:"," GPRS-TESTGRUPPE","       ", P&Leer15,						ASCII_FORM, 0, P&hid4,	V0, 0, 0},
	{" ->;"," Work Delay Ctr "," sek   ", P&gprs_error_handling.ui_work_delay_ctr,						US_INT, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Work Reset Val "," sek   ", P&gprs_error_handling.ui_reset_delay_value,				US_INT, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Work Reset Ctr "," sek   ", P&gprs_error_handling.ui_reset_delay_ctr,					US_INT, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Reinit Counter ","       ", P&gprs_error_handling.uc_reinit_counter,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Modem Reset Ctr","       ", P&gprs_error_handling.uc_modem_reset_counter,			US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," R66 Reset Ctr  ","       ", P&gprs_error_handling.uc_r66_reset_counter,				US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Wrong Adr ctr  ","       ", P&gprs_error_handling.uc_wrong_address_counter,		US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 00;"," Error Code 1   ","       ", P&gprs_error_handling.memory[0].uc_error_code,			US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 01;"," Error Telegr 1 ","       ", P&gprs_error_handling.memory[0].ucf_telegram[0],		HEXBUF_FORM,	0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 1 Std","       ", P&gprs_error_handling.memory[0].uc_std,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 1 Min","       ", P&gprs_error_handling.memory[0].uc_min,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 1 Sek","       ", P&gprs_error_handling.memory[0].uc_sec,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 02;"," Error Code 2   ","       ", P&gprs_error_handling.memory[1].uc_error_code,			US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 03;"," Error Telegr 2 ","       ", P&gprs_error_handling.memory[1].ucf_telegram[0],		HEXBUF_FORM,	0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 2 Std","       ", P&gprs_error_handling.memory[1].uc_std,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 2 Min","       ", P&gprs_error_handling.memory[1].uc_min,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 2 Sek","       ", P&gprs_error_handling.memory[1].uc_sec,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 04;"," Error Code 3   ","       ", P&gprs_error_handling.memory[2].uc_error_code,			US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 05;"," Error Telegr 3 ","       ", P&gprs_error_handling.memory[2].ucf_telegram[0],		HEXBUF_FORM,	0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 3 Std","       ", P&gprs_error_handling.memory[2].uc_std,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 3 Min","       ", P&gprs_error_handling.memory[2].uc_min,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 3 Sek","       ", P&gprs_error_handling.memory[2].uc_sec,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 06;"," Error Code 4   ","       ", P&gprs_error_handling.memory[3].uc_error_code,			US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 07;"," Error Telegr 4 ","       ", P&gprs_error_handling.memory[3].ucf_telegram[0],		HEXBUF_FORM,	0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 4 Std","       ", P&gprs_error_handling.memory[3].uc_std,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 4 Min","       ", P&gprs_error_handling.memory[3].uc_min,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 4 Sek","       ", P&gprs_error_handling.memory[3].uc_sec,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 08;"," Error Code 5   ","       ", P&gprs_error_handling.memory[4].uc_error_code,			US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 09;"," Error Telegr 5 ","       ", P&gprs_error_handling.memory[4].ucf_telegram[0],		HEXBUF_FORM,	0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 5 Std","       ", P&gprs_error_handling.memory[4].uc_std,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 5 Min","       ", P&gprs_error_handling.memory[4].uc_min,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 5 Sek","       ", P&gprs_error_handling.memory[4].uc_sec,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 10;"," Error Code 6   ","       ", P&gprs_error_handling.memory[5].uc_error_code,			US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 11;"," Error Telegr 6 ","       ", P&gprs_error_handling.memory[5].ucf_telegram[0],		HEXBUF_FORM,	0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 6 Std","       ", P&gprs_error_handling.memory[5].uc_std,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 6 Min","       ", P&gprs_error_handling.memory[5].uc_min,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 6 Sek","       ", P&gprs_error_handling.memory[5].uc_sec,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 12;"," Error Code 7   ","       ", P&gprs_error_handling.memory[6].uc_error_code,			US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 13;"," Error Telegr 7 ","       ", P&gprs_error_handling.memory[6].ucf_telegram[0],		HEXBUF_FORM,	0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 7 Std","       ", P&gprs_error_handling.memory[6].uc_std,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 7 Min","       ", P&gprs_error_handling.memory[6].uc_min,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 7 Sek","       ", P&gprs_error_handling.memory[6].uc_sec,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 14;"," Error Code 8   ","       ", P&gprs_error_handling.memory[7].uc_error_code,			US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 15;"," Error Telegr 8 ","       ", P&gprs_error_handling.memory[7].ucf_telegram[0],		HEXBUF_FORM,	0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 8 Std","       ", P&gprs_error_handling.memory[7].uc_std,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 8 Min","       ", P&gprs_error_handling.memory[7].uc_min,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 8 Sek","       ", P&gprs_error_handling.memory[7].uc_sec,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 16;"," Error Code 9   ","       ", P&gprs_error_handling.memory[8].uc_error_code,			US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 17;"," Error Telegr 9 ","       ", P&gprs_error_handling.memory[8].ucf_telegram[0],		HEXBUF_FORM,	0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 9 Std","       ", P&gprs_error_handling.memory[8].uc_std,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 9 Min","       ", P&gprs_error_handling.memory[8].uc_min,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp 9 Sek","       ", P&gprs_error_handling.memory[8].uc_sec,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 18;"," Error Code 10  ","       ", P&gprs_error_handling.memory[9].uc_error_code,			US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 19;"," Error Telegr 10","       ", P&gprs_error_handling.memory[9].ucf_telegram[0],		HEXBUF_FORM,	0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp10 Std","       ", P&gprs_error_handling.memory[9].uc_std,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp10 Min","       ", P&gprs_error_handling.memory[9].uc_min,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Timestamp10 Sek","       ", P&gprs_error_handling.memory[9].uc_sec,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 20;"," Error Code Idx "," 0..9  ", P&gprs_error_handling.uc_error_code_idx,						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" 21;"," rx overflow ctr","       ", P&gprs_error_handling.ui_buffer_overflow_ctr,      US_INT, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Sim ID         ","       ", P&gprs_modem_info.ucf_sim_id[0],										ASCII_FORM,  15, 	P&hid4,		V0, 0, 0},
	{" ->;"," Sim ID         ","       ", P&gprs_modem_info.ucf_sim_id[16],									ASCII_FORM,   5, 	P&hid4,		V0, 0, 0},
	{" ->;"," IMEI           ","       ", P&gprs_modem_info.ucf_imei[0],											ASCII_FORM,  16, 	P&hid4,		V0, 0, 0},
	{" ->;"," Modul Type     ","       ", P&gprs_modem_info.ucf_modul[0],										ASCII_FORM,   6, 	P&hid4,		V0, 0, 0},
	{" ->;"," MCC            ","       ", P&gprs_modem_info.ui_mcc,													US_INT, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," MNC            ","       ", P&gprs_modem_info.ui_mnc,													US_INT, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," LAC            ","       ", P&gprs_modem_info.ui_lac,													US_INT, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," CI             ","       ", P&gprs_modem_info.ui_ci,														US_INT, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," RSSI           ","       ", P&gprs_modem_info.uc_rssi,													US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{"[->;"," RX Buffer Tel  ","       ", P&ucf_rx_buffer[0],																HEXBUF_FORM,	0, 	P&hid4,		V0, 0, 0},
	{"[->;"," TX Buffer Tel  ","       ", P&ucf_tx_buffer[0],																HEXBUF_FORM,	0, 	P&hid4,		V0, 0, 0},
	{"[->;"," RX Buffer LP   ","       ", P&RxBuf_LP[0],																			HEXBUF_FORM,	0, 	P&hid4,		V0, 0, 0},
	{"[->;"," TX Buffer LP   ","       ", P&TxBuf_LP[0],																			HEXBUF_FORM,	0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Main State     ","       ", P&uc_gprs_main_state,                   						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Init State     ","       ", P&uc_gprs_init_state,                   						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Work State     ","       ", P&uc_gprs_work_state,                   						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Choice         ","       ", P&uc_gprs_choice,                       						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," Responce Code  ","       ", P&uc_gprs_responcecode,                 						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," rx start index ","       ", P&uc_gprs_rx_start_idx,                 						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," telegr ready   ","       ", P&uc_gprs_rx_telegram_ready,            						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," timeout value  ","       ", P&ui_gprs_rx_timeout_value,               					US_INT, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," timeout ctr    ","       ", P&ui_gprs_rx_timeout_ctr,               						US_INT, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," rx lenght      ","       ", P&uc_gprs_rx_lenght,                    						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," overflow requer","       ", P&uc_gprs_rx_buffer_overflow_requered,  						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," TransparentMode","       ", P&uc_gprs_transperantmode_activ,        						US_CHAR, 			0, 	P&hid4,		V0, 0, 0},
	{" ->;"," work handler   ","       ", P&ui_gprs_work_handler,        										US_INT, 			0, 	P&hid4,		V0, 0, 0},
} 

const Pgrup qsm[] = { 
	{"***:"," QUITTIERBARE   ","       ", P&Stoermeld,							 ASCII_FORM, 0, P&vis,	V1, 0, 0},
	{"*01:"," QSM VORHANDEN ?","       ", P&un_qsm,			 						JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	//**PARSER-BEGIN-qsm[]**  AUTOMATISCHE ERZEUGUNG *****
	//**PARSER-ENDE-qsm[]**  AUTOMATISCHE ERZEUGUNG *****
	{" 99:"," QUITTIER-TASTE "," EIN=1 ", P&quit_taste,			 						US_CHAR, 0, P&vis,	V1, 0, 0},
	{" ->;"," QUITTIER-TASTE ","       ", P&QUITTS[0],			 			JANEIN_FORMIP, 2, P&hid4,	V0, 0, 0},
} 

const Pgrup wp1[] = { 
	{"***:"," WAERMEPUMPE    ","       ", P&Wpmod,							ASCII_FORM, 0, P&vis,		V1},
	{"*01:"," TV-SWP         "," C    ", P&TV_WP[WP1],						 	ANA_FORMP, 1, P&vis,		V1, 0, 0},
	{"*01:"," TV-SWP         "," C    ", P&TV_WP[WP1],					 ANA_FORMP, 0x81, P&kom,		E1, FUEHLER, 0},
	{"*02:"," TR-SWP         "," C    ", P&TR_WP[WP1],						 	ANA_FORMP, 1, P&vis,		V1, 0, 0},
	{"*02:"," TR-SWP         "," C    ", P&TR_WP[WP1],					 ANA_FORMP, 0x81, P&kom,		E1, FUEHLER, 0},
	{"*03:"," TSPo-SWP       "," C    ", P&TSPo_WP[WP1],						 	ANA_FORMP, 1, P&vis,		V1, 0, 0},
	{"*03:"," TSPo-SWP       "," C    ", P&TSPo_WP[WP1],					 ANA_FORMP, 0x81, P&kom,		E1, FUEHLER, 0},
	{"*05:"," TSPu-SWP       "," C    ", P&TSPu_WP[WP1],						 	ANA_FORMP, 1, P&vis,		V1, 0, 0},
	{"*05:"," TSPu-SWP       "," C    ", P&TSPu_WP[WP1],					 ANA_FORMP, 0x81, P&kom,		E1, FUEHLER, 0},
	{"*08:"," TVQ-SWP        "," C    ", P&TVQ_WP[WP1],						 	ANA_FORMP, 1, P&vis,		V1, 0, 0},
	{"*08:"," TVQ-SWP        "," C    ", P&TVQ_WP[WP1],					 ANA_FORMP, 0x81, P&kom,		E1, FUEHLER, 0},
	{"*09:"," TRQ-SWP        "," C    ", P&TRQ_WP[WP1],						 	ANA_FORMP, 1, P&vis,		V1, 0, 0},
	{"*09:"," TRQ-SWP        "," C    ", P&TRQ_WP[WP1],					 ANA_FORMP, 0x81, P&kom,		E1, FUEHLER, 0},
	{"*->:"," BM ModBus DIMP ","       ", P&wpd[WP1].ch_BM_WPU_MB, 	JANEIN_FORM, 2, P&vis,		V0, 0, 0},
	{"*22:"," VL BER HK1     "," C    ", P&hkd[HK1].tvsb,					US_INT, 1, P&vis,		V0, 0, 0},
	{" 23;"," ANFORD.  Offset"," C    ", P&wps[WP1].T_Sollwert_Offset,	 S_INT, 1, P&hid1,	V0, 0, 0},
	{"*24:"," E: TWE-ANF E/A "," 1=EIN ", P&station1_ea,				 		ANA_FORM, 0, P&vis, 	V0, 0, 0},
	{" 27;"," Manu ANFORD.   "," HAND=1", P&wps[WP1].Para_Manu_Sollwert, US_CHAR, 0, P&hid1,	V1, 0, 0},
	{" ->;"," ANFORDERUNG    "," C    ", P&wps[WP1].T_manu_Sollwert,US_INT, 1, P&hid1,	V1, 0, 0},
	{"*28:"," ANFORD.  AKTIV "," C    ", P&wpd[WP1].Eingehender_Sollwert,	S_INT, 1, P&vis, 	V1, 0, 0},
	{" ->;"," Min Anf. AKTIV "," C    ", P&wps[WP1].iPa_T_Sollwert_IN_MIN,	S_INT, 1, P&hid1,	V1, 0, 0},
	{" ->;"," Max Anf. AKTIV "," C    ", P&wps[WP1].iPa_T_Sollwert_IN_MAX,	S_INT, 1, P&hid1,	V1, 0, 0},
	{"*30:"," Sollwert AA    "," C    ", P&maxAnford,				 				 S_INT, 1, P&vis, 	V1, 0, 0},
	{" ->;"," TEMP.Sollw.MIN "," C    ", P&TmanfSkalMin,							 S_INT, 1, P&hid1,	V0, 0, 0},
	{" ->;"," SPG.Sollw.MIN  "," Volt  ", P&TmanfSkalMinSpg,					 S_INT, 2, P&hid1,	V0, 0, 0},
	{" ->;"," TEMP.Sollw.MAX "," C    ", P&TmanfSkalMax,							 S_INT, 1, P&hid1,	V0, 0, 0},
	{" ->;"," SPG.Sollw.MAX  "," Volt  ", P&TmanfSkalMaxSpg,					 S_INT, 2, P&hid1,	V0, 0, 0},
	{"*->;"," ausgabe tmanf  "," Volt  ", P&TMANF[0],							AOUT_FORMP, 2, P&hid2,	V0, 0, 0},
	{" 31:"," Sollwert E/A ? "," EIN=1 ", P&wps[WP1].Sollwert_EA,		 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," SOLLW SWP HEI  "," C    ", P&wps[WP1].intPa_Sollwert_HEI,	S_INT, 1, P&hid1_SOLLW_EA,	V0, 0, 0},
	{" ->;"," SOLLW SWP AUS  "," C    ", P&wps[WP1].intPa_Sollwert_AUS,	S_INT, 1, P&hid1_SOLLW_EA,	V0, 0, 0},
	{" ->;"," SOLLW SWP TWE  "," C    ", P&wps[WP1].intPa_Sollwert_TWE,	S_INT, 1, P&hid1,	V0, 0, 0},
	{"*32:"," FREIGABE SWP   ","       ", P&DA_UNI[U1],	 			   JANEIN_FORMOP, 2, P&vis,		V0, 0, 0},
	{" 33;"," Manu FREIG SWP "," HAND=1", P&wps[WP1].WPU_Freigabe_Haut, US_CHAR, 0, P&hid1,	V1, 0, 0},
	{" ->:"," SWP FRE EIN/AUS"," EIN=1 ", P&wps[WP1].WPU_Freigabe_Hand_stellen, US_CHAR, 0, P&hid1,	V1, 0, 0},
	{"*34:"," FREIG TWE VORRA","       ", P&DA_UNI[U2],	 			   JANEIN_FORMOP, 2, P&vis,		V0, 0, 0},
	{" 35;"," Manu TWE VORRA "," HAND=1", P&wps[WP1].chPa_Freiagbe_TWE_Hau, US_CHAR, 0, P&hid1,	V1, 0, 0},
	{" ->:"," TWE VOR EIN/AUS"," EIN=1 ", P&wps[WP1].chPa_Freiagbe_TWE_Hand_stellen, US_CHAR, 0, P&hid1,	V1, 0, 0},
	{"*36:"," UV SWP AUF ?   ","       ", P&DA_UNI[U3],	 			   JANEIN_FORMOP, 2, P&vis,		V0, 0, 0},
	{" 37;"," Manu UV SWP    "," HAND=1", P&wps[WP1].chPa_uv_Hau, US_CHAR, 0, P&hid1,	V1, 0, 0},
	{" ->:"," UV SWP STELLEN "," AUF=1 ", P&wps[WP1].chPa_uv_Hand_stellen, US_CHAR, 0, P&hid1,	V1, 0, 0},
	{" ->;"," Verzoegerungz  "," min   ", P&wps[WP1].chPa_Verzoegerung_min,		 US_CHAR, 0, P&hid1,	V1, 0, 0},
	{" ->:"," Verzoegerun_Cnt"," s     ", P&wpd[WP1].Verzoegerungszeit_Cnt,		  US_INT, 0, P&hid1,	V0, 0, 0},
	{" ->;"," Mindestlaufz   "," min   ", P&wps[WP1].chPa_Mindestlaufzeit_min,		 US_CHAR, 0, P&hid1,	V1, 0, 0},
	{" ->:"," Mindestlauf_Cnt"," s     ", P&wpd[WP1].Mindestlaufzeit_Cnt,		  US_INT, 0, P&hid1,	V0, 0, 0},
	{" ->;"," Sperrzeit      "," min   ", P&wps[WP1].chPa_Sperrzeit_min,		 US_CHAR, 0, P&hid1,	V1, 0, 0},
	{" ->:"," Sperrzeit_Cnt  "," s     ", P&wpd[WP1].Sperrzeit_Cnt,		  US_INT, 0, P&hid1,	V0, 0, 0},
	{"*->:"," freigabe swp   ","       ", P&wpd[WP1].Status_WPU_Freigabe_oZeit, JANEIN_FORM, 2, P&vis,		V0, 0, 0},
	{"*38:"," VENTILSTELLUNG "," %     ", P&AA_UNI[U1],								AOUT_FORMP, 1, P&vis,	V1, 0, 0},
	{" 39;"," HAND RV SWP    "," HAND=1", P&wps[WP1].chpa_rv_Hau,				 US_CHAR, 0, P&hid1,	V1, 0, 0},
	{" ->;"," RV SWP stellen "," %     ", P&wps[WP1].ipa_rv_stellung,			 US_INT, 1, P&hid1,	V1, 0, 0},
	{" 40:"," Strategie      "," 1-2   ", P&wps[WP1].chPa_Strategie, US_CHAR, 0, P&hid1,		V1, 0, 0},
	{"*41:"," Quellenschutz ?","       ", P&wpd[WP1].Status_Quellenschutz, JANEIN_FORM, 2, P&vis,		V1, 0, 0},
	{" ->;"," Quellenminimum "," C    ", P&wps[WP1].intPa_Quellentemperaturminimum,	S_INT, 1, P&hid1,	V1, 0, 0},
	{"*->;"," Aktive Temp.   "," C    ", P&wpd[WP1].intT_Quellentemperatur_aktiv,	  S_INT, 1, P&hid1,	V0, 0, 0},
	{"*42:"," Frostschutz   ?","       ", P&wpd[WP1].Status_Frostschutz, JANEIN_FORM, 2, P&vis,		V1, 0, 0},
	{" ->;"," Speicherminimum"," C    ", P&wps[WP1].intPa_Speicherminimum,	S_INT, 1, P&hid1,	V1, 0, 0},
	{"*->;"," Aktive Temp.   "," C    ", P&wpd[WP1].intT_Speichertemperatur_aktiv,	  S_INT, 1, P&hid1,	V0, 0, 0},
	{"*43:"," Speicherladung?","       ", P&wpd[WP1].Status_Speicherladung, JANEIN_FORM, 2, P&hid1_dS1,		V1, 0, 0},
	{" ->;"," dT Ladung ein ?"," K     ", P&wps[WP1].intPa_T_Speicherladung_on,	S_INT, 1, P&hid1_dS1,	V1, 0, 0},
	{" ->;"," dT Ladung aus ?"," K     ", P&wps[WP1].intPa_T_Speicherladung_off,	S_INT, 1, P&hid1_dS1,	V1, 0, 0},
	{"*->;"," Ladebeginn TSPo"," C    ", P&wpd[WP1].intT_Ladebginn,	  S_INT, 1, P&hid1_dS1,	V0, 0, 0},
	{"*->;"," Ladeende TSPu  "," C    ", P&wpd[WP1].intT_Ladeende,	  S_INT, 1, P&hid1_dS1,	V0, 0, 0},
	{"*43:"," Rueckl.-Regel ?","       ", P&wpd[WP1].Status_Speicherladung, JANEIN_FORM, 2, P&hid1_dS2,		V0, 0, 0},
	{" ->;"," dT RL ein     ?"," K     ", P&wps[WP1].intPa_T_Speicherladung_on,	S_INT, 1, P&hid1_dS2,	V0, 0, 0},
	{" ->;"," dT RL aus     ?"," K     ", P&wps[WP1].intPa_T_Speicherladung_off,	S_INT, 1, P&hid1_dS2,	V0, 0, 0},
	{"*->;"," RL-Beg. TR-SWP "," C    ", P&wpd[WP1].intT_Ladebginn,	  S_INT, 1, P&hid1_dS2,	V0, 0, 0},
	{"*->;"," RL-Ende TR-SWP "," C    ", P&wpd[WP1].intT_Ladeende,	  S_INT, 1, P&hid1_dS2,	V0, 0, 0},
	{"*44:"," Warmwasservor.?","       ", P&wpd[WP1].Status_WW_Vorrang, JANEIN_FORM, 2, P&vis,		V1, 0, 0},
	{" ->;"," Maximale Dauer "," min   ", P&wps[WP1].chPa_TWE_Maxlaufzeit_min,		 US_CHAR, 0, P&hid1,	V1, 0, 0},
	{" ->:"," Max. Dauer_Cnt "," s     ", P&wpd[WP1].i_TWE_Maxzeit_Cnt,		  US_INT, 0, P&hid1,	V0, 0, 0},
	{" ->;"," Sperrzeit      "," min   ", P&wps[WP1].chPa_TWE_Sperrzeit_min,		 US_CHAR, 0, P&hid1,	V1, 0, 0},
	{" ->:"," Sperrzeit_Cnt  "," s     ", P&wpd[WP1].i_TWE_Sperrzeit_Cnt,		  US_INT, 0, P&hid1,	V0, 0, 0},
	{"*45:"," WPU-HEIZEN ?   ","       ", P&wpd[WP1].chPa_WPU_HEI, 		 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
	{"*46:"," WPU-TWE VORRA ?","       ", P&wpd[WP1].chPa_WPU_TWE, 		 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
	{" 80;"," P-VERSTAERKUNG "," %/m/h", P&wps[0].Kp,						US_INT, 2, P&hid1,	V0, 0, 0},
	{" ->;"," D-VERSTAERKUNG ","       ", P&wps[0].Kd,						US_INT, 2, P&hid1,	V0, 0, 0},
	{" ->;"," TASTZEIT       "," s     ", P&wps[0].Ts,						US_INT, 1, P&hid1,	V0, 0, 0},
	{" ->;"," NACHSTELLZEIT  "," s     ", P&wps[0].Tn,						US_INT, 1, P&hid1,	V0, 0, 0},
	{" 81;"," VENTILSTELL.MIN"," %     ", P&wps[0].Y_rel_min,	 		US_INT, 1, P&hid1,	V0, 0, 0},
	{" 82;"," VENTILSTELL.MAX"," %     ", P&wps[0].Y_rel_max,	 		US_INT, 1, P&hid1,	V0, 0, 0},
	{" ->;"," OEFFNUNGSBEGINN"," %     ", P&wps[0].Y_rel_beg,	 		US_INT, 1, P&hid1,	V0, 0, 0},
	{"*83;"," IST VOLSTR. WSP"," m/h  ", P&wmengCtr[2].flow_h,			US_LONG, 2, P&hid1,	V0, 0, 0},
	{" 84;"," SOLL Vol. WPU  "," m/h  ", P&wps[0].iPa_Vol_ist,		US_INT, 1, P&hid1,	V1, 0, 0},
	{"*85;"," REGELABWEICHUNG"," m/h  ", P&wpd[0].ei,						 S_INT, 2, P&hid1,	V0, 0, 0},
	{"*->;"," dy_rel         ","       ", P&wpd[0].dy_rel,				 S_INT, 3, P&hid2,	V0, 0, 0},
	{"*86:"," VENTILSTELLUNG "," %     ", P&AA_UNI[U1],					AOUT_FORMP, 1, P&vis,	V0, 0, 0},
} 

const Pgrup sys[] = { 
	{"***;"," SYSTEM-ANZEIGEN","       ", P&Ein_Ausg,					ASCII_FORM, 0, P&hid1,	V0, 0, 0},
	{" 00;"," PARAM. SICHERN "," JA=1  ", P&bicmove_wunsch,	BICMOVE_FORM, 0, P&hid1,	V0, 0, 0},
	{"*01;"," SENSOR_IN1 TEMP"," C    ", P&pt_mewe[0].messw,		ANA_FORM, 1, P&hid1,	V0, 0, 0},
	{" 01;"," SENSOR_IN1 KORR"," Ohm   ", P&Pt_Korr[0],						 S_INT, 1, P&hid1,	V0, 0, 0},
	{" 01;"," SENSOR_IN1 FILT"," 0-9   ", P&Pt_Filt[0],					 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 01;"," SENSOR_IN1 TYP ","       ", P&Tp_Type[0],				 FTYP_FORM, 0, P&hid1,	V0, 0, 0},
	{"*02;"," SENSOR_IN2 TEMP"," C    ", P&pt_mewe[1].messw,		ANA_FORM, 1, P&hid1,	V0, 0, 0},
	{" 02;"," SENSOR_IN2 KORR"," Ohm   ", P&Pt_Korr[1],						 S_INT, 1, P&hid1,	V0, 0, 0},
	{" 02;"," SENSOR_IN2 FILT"," 0-9   ", P&Pt_Filt[1],					 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 02;"," SENSOR_IN2 TYP ","       ", P&Tp_Type[1],					FTYP_FORM, 0, P&hid1,	V0, 0, 0},
	{"*03;"," SENSOR_IN3 TEMP"," C    ", P&pt_mewe[2].messw,		ANA_FORM, 1, P&hid1,	V0, 0, 0},
	{" 03;"," SENSOR_IN3 KORR"," Ohm   ", P&Pt_Korr[2],						 S_INT, 1, P&hid1,	V0, 0, 0},
	{" 03;"," SENSOR_IN3 FILT"," 0-9   ", P&Pt_Filt[2],					 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 03;"," SENSOR_IN3 TYP ","       ", P&Tp_Type[2],				 FTYP_FORM, 0, P&hid1,	V0, 0, 0},
	{"*04;"," SENSOR_IN4 TEMP"," C    ", P&pt_mewe[3].messw,		ANA_FORM, 1, P&hid1,	V0, 0, 0},
	{" 04;"," SENSOR_IN4 KORR"," Ohm   ", P&Pt_Korr[3],						 S_INT, 1, P&hid1,	V0, 0, 0},
	{" 04;"," SENSOR_IN4 FILT"," 0-9   ", P&Pt_Filt[3],					 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 04;"," SENSOR_IN4 TYP ","       ", P&Tp_Type[3],				 FTYP_FORM, 0, P&hid1,	V0, 0, 0},
	{"*05;"," SENSOR_IN5 TEMP"," C    ", P&pt_mewe[4].messw,		ANA_FORM, 1, P&hid1,	V0, 0, 0},
	{" 05;"," SENSOR_IN5 KORR"," Ohm   ", P&Pt_Korr[4],						 S_INT, 1, P&hid1,	V0, 0, 0},
	{" 05;"," SENSOR_IN5 FILT"," 0-9   ", P&Pt_Filt[4],					 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 05;"," SENSOR_IN5 TYP ","       ", P&Tp_Type[4],				 FTYP_FORM, 0, P&hid1,	V0, 0, 0},
	{"*06;"," SENSOR_IN6 TEMP"," C    ", P&pt_mewe[5].messw,		ANA_FORM, 1, P&hid1,	V0, 0, 0},
	{" 06;"," SENSOR_IN6 KORR"," Ohm   ", P&Pt_Korr[5],						 S_INT, 1, P&hid1,	V0, 0, 0},
	{" 06;"," SENSOR_IN6 FILT"," 0-9   ", P&Pt_Filt[5],					 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 06;"," SENSOR_IN6 TYP ","       ", P&Tp_Type[5],				 FTYP_FORM, 0, P&hid1,	V0, 0, 0},
	{"*07;"," SENSOR_IN7 TEMP"," C    ", P&pt_mewe[6].messw,		ANA_FORM, 1, P&hid1,	V0, 0, 0},
	{" 07;"," SENSOR_IN7 KORR"," Ohm   ", P&Pt_Korr[6],						 S_INT, 1, P&hid1,	V0, 0, 0},
	{" 07;"," SENSOR_IN7 FILT"," 0-9   ", P&Pt_Filt[6],					 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 07;"," SENSOR_IN7 TYP ","       ", P&Tp_Type[6],				 FTYP_FORM, 0, P&hid1,	V0, 0, 0},
	{"*08;"," SENSOR_IN8 TEMP"," C    ", P&pt_mewe[7].messw,		ANA_FORM, 1, P&hid1,	V0, 0, 0},
	{" 08;"," SENSOR_IN8 KORR"," Ohm   ", P&Pt_Korr[7],						 S_INT, 1, P&hid1,	V0, 0, 0},
	{" 08;"," SENSOR_IN8 FILT"," 0-9   ", P&Pt_Filt[7],					 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 08;"," SENSOR_IN8 TYP ","       ", P&Tp_Type[7],				 FTYP_FORM, 0, P&hid1,	V0, 0, 0},
	{" 09;"," SENSOR-IN LIFE "," 1-8   ", P&Pt_Life,			 			 DIGL_FORM, 8, P&hid1,	V0, 0, 0},
	{" 10;"," ANALOG-IN LIFE "," 3-10  ", P&AE_Life,			 			 DIGL_FORM, 8, P&hid1,	V0, 0, 0},
	{"*11;"," ANALOG_IN3     "," Volt  ", P&ae_mewe[0].messw,		ANA_FORM, 2, P&hid1,	V0, 0, 0},
	{"*12;"," ANALOG_IN4     "," Volt  ", P&ae_mewe[1].messw,		ANA_FORM, 2, P&hid1,	V0, 0, 0},
	{"*13;"," ANALOG_IN5     "," Volt  ", P&ae_mewe[2].messw,		ANA_FORM, 2, P&hid1,	V0, 0, 0},
	{"*14;"," ANALOG_IN6     "," Volt  ", P&ae_mewe[3].messw,		ANA_FORM, 2, P&hid1,	V0, 0, 0},
	{"*15;"," ANALOG_IN7     "," Volt  ", P&ae_mewe[4].messw,		ANA_FORM, 2, P&hid1,	V0, 0, 0},
	{"*16;"," ANALOG_IN8     "," Volt  ", P&ae_mewe[5].messw,		ANA_FORM, 2, P&hid1,	V0, 0, 0},
	{"*17;"," ANALOG_IN9     "," Volt  ", P&ae_mewe[6].messw,		ANA_FORM, 2, P&hid1,	V0, 0, 0},
	{"*18;"," ANALOG_IN10    "," Volt  ", P&ae_mewe[7].messw,		ANA_FORM, 2, P&hid1,	V0, 0, 0},
	{"*31;"," ANALOG-AUSGANG1"," Volt  ", P&AoutSk[0],							US_INT, 2, P&hid1,	V0, 0, 0},
	{" ->;"," SKALIERUNG 0%  "," Volt  ", P&AASkal[0].NullP,				US_INT, 2, P&hid1,	V0, 0, 0},
	{" ->;"," SKALIERUNG 100%"," Volt  ", P&AASkal[0].HundP,				US_INT, 2, P&hid1,	V0, 0, 0},
	{"*32;"," ANALOG-AUSGANG2"," Volt  ", P&AoutSk[1],							US_INT, 2, P&hid1,	V0, 0, 0},
	{" ->;"," SKALIERUNG 0%  "," Volt  ", P&AASkal[1].NullP,				US_INT, 2, P&hid1,	V0, 0, 0},
	{" ->;"," SKALIERUNG 100%"," Volt  ", P&AASkal[1].HundP,				US_INT, 2, P&hid1,	V0, 0, 0},
	{"*33;"," DIGITAL-EINGANG"," IN3-10", P&Diginp,						DIGAE_FORM, 8, P&hid1,	V0, 0, 0},
	{"*34;"," DE BRUCH(NAMUR)"," IN3-10", P&Bruch,							DIGAE_FORM, 8, P&hid1,	V0, 0, 0},
	{"*35;"," DE KURZ (NAMUR)"," IN3-10", P&Kurz,							DIGAE_FORM, 8, P&hid1,	V0, 0, 0},
	{"*36;"," DIGITAL-AUSGANG"," 1-6   ", P&Digout,			 			 DIGL_FORM, 6, P&hid1,	V0, 0, 0},
	{" 37;"," AUSSENTEMP BC  "," C    ", P&Ta1Bc,									 S_INT, 1, P&hid1,	V0, 0, 0},
	{"*38;"," COUNTDOWN  BC  "," min   ", P&CountDwBc,						 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 39;"," VORRANG    BC  "," JA=1  ", P&bc_vorra,						 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 40;"," SIMULIER   BC  "," min   ", P&bc_simu,						 	 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," Cool BC        ","       ", P&CoolBc,					 	 DIGR_FORM, 8, P&hid2,	V0, 0, 0},
	{" ->;"," Cool BC Status ","       ", P&CoolBcStat,			 	 DIGR_FORM, 8, P&hid2,	V0, 0, 0},
	{" ->;"," Heat BC        ","       ", P&HeatBc,					 	 DIGR_FORM, 8, P&hid2,	V0, 0, 0},
	{" ->;"," Heat BC Status ","       ", P&HeatBcStat,			 	 DIGR_FORM, 8, P&hid2,	V0, 0, 0},
	{" ->;"," C.down CoolHeat"," min   ", P&CountDwBcStat,			 	 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" ->;"," Sperre Broadc. "," JA=1  ", P&bc_sperre,						 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" ->;"," Aktuelle Ta    "," C    ", P&ta,									ANA_FORM, 1, P&hid2,	V0, 0, 0},
	{" 51;"," BUS X0 G1 R38_1","       ", P&mod38[0].bus,				 				 US_CHAR, 0, P&r38vis[0],	V0, 0, 0},
	{" 52;"," ADR       R38_1","       ", P&mod38[0].adr,								 US_CHAR, 0, P&r38vis[0],	V0, 0, 0},
	{"*53;"," DAT-ERROR R38_1","       ", P&mod38[0].error,	 				 JANEIN_FORM, 0, P&r38vis[0],	E1, MODULE, 0},
	{"054;"," PROJ.EING R38_1","       ", P&mod38[0].inpUsed,					 DIGL_FORM,14, P&r38vis[0],	V0, 0, 0},
	{"055;"," LIFE.EING R38_1","       ", P&mod38[0].life,							 DIGL_FORM,14, P&r38vis[0],	V0, 0, 0},
	{"*->;"," PT_IN1    R38_1"," C    ", P&mod38[0].pt_mewe[0].messw,		ANA_FORM, 1, P&r38vis[0],	V0, 0, 0},
	{"*->;"," PT_IN2    R38_1"," C    ", P&mod38[0].pt_mewe[1].messw,		ANA_FORM, 1, P&r38vis[0],	V0, 0, 0},
	{"*->;"," PT_IN3    R38_1"," C    ", P&mod38[0].pt_mewe[2].messw,		ANA_FORM, 1, P&r38vis[0],	V0, 0, 0},
	{"*->;"," PT_IN4    R38_1"," C    ", P&mod38[0].pt_mewe[3].messw,		ANA_FORM, 1, P&r38vis[0],	V0, 0, 0},
	{"*->;"," PT_IN5    R38_1"," C    ", P&mod38[0].pt_mewe[4].messw,		ANA_FORM, 1, P&r38vis[0],	V0, 0, 0},
	{"*->;"," PT_IN6    R38_1"," C    ", P&mod38[0].pt_mewe[5].messw,		ANA_FORM, 1, P&r38vis[0],	V0, 0, 0},
	{"*->;"," PT_IN7    R38_1"," C    ", P&mod38[0].pt_mewe[6].messw,		ANA_FORM, 1, P&r38vis[0],	V0, 0, 0},
	{"*->;"," PT_IN8    R38_1"," C    ", P&mod38[0].pt_mewe[7].messw,		ANA_FORM, 1, P&r38vis[0],	V0, 0, 0},
	{"*->;"," PT_IN9    R38_1"," C    ", P&mod38[0].pt_mewe[8].messw,		ANA_FORM, 1, P&r38vis[0],	V0, 0, 0},
	{"*->;"," PT_IN10   R38_1"," C    ", P&mod38[0].pt_mewe[9].messw,		ANA_FORM, 1, P&r38vis[0],	V0, 0, 0},
	{"*->;"," PT_IN11   R38_1"," C    ", P&mod38[0].pt_mewe[10].messw,	ANA_FORM, 1, P&r38vis[0],	V0, 0, 0},
	{"*->;"," PT_IN12   R38_1"," C    ", P&mod38[0].pt_mewe[11].messw,	ANA_FORM, 1, P&r38vis[0],	V0, 0, 0},
	{"*->;"," PT_IN13   R38_1"," C    ", P&mod38[0].pt_mewe[12].messw,	ANA_FORM, 1, P&r38vis[0],	V0, 0, 0},
	{"*->;"," PT_IN14   R38_1"," C    ", P&mod38[0].pt_mewe[13].messw,	ANA_FORM, 1, P&r38vis[0],	V0, 0, 0},
	{"*80;"," RESET COUNTER  ","       ", P&Resetcnt,							US_INT, 0, P&hid1,	V1, 0, 0},
	{"*->;"," RESET DATUM    ","       ", P&reset_date,			 	 DATE_FORM, 1, P&hid1,	V0, 0, 0},
	{"*->;"," RESET UHRZEIT  ","       ", P&reset_time,			 	 DATE_FORM, 2, P&hid1,	V0, 0, 0},
	{"*81;"," BOARD I2C ERROR"," 0=NEIN", P&BIC_Error,			 			 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{"*82;"," RTC-UHR ERROR  ","       ", P&rtc_error,				 JANEIN_FORM, 0, P&hid1,	E1, EREIGNIS, 0},
	{"*83;"," MAIN-CRASH:TASK","       ", P&noi_reanimate,			 TASK_FORM, 0, P&hid1,	E1, EREIGNIS, 0},
	{"*84;"," ARCHIVIERUNG ? ","       ", P&archivAktiv,		 JANEIN_FORM, 0, P&hid1,		V0, 0, 0},
	{"*85;"," ANZAHL ARCH-DAE","       ", P&arch_par,				US_CHAR, 		0, P&hid1,	V0, 0, 0},
	{"*86;"," SDM-ARCH-STATUS","       ", P&a_erg_text,	 DYN_ASCII_FORM, 0, P&hid1,	V0, 0, 0},
	{"*87;"," SDM-CARD-STATUS","       ", P&c_erg_text,	 DYN_ASCII_FORM, 0, P&hid1,	V0, 0, 0},
	{"*88;"," SDM-AKT-DAE,EXP","       ", P&sdm_akt_dae,		  		US_INT,  2, P&hid1,	V0, 0, 0},
	{" ->;"," SDM-ARCHIV-INIT","       ", P&werks_sdm_code,		  US_INT,  2, P&hid1,	V1, 0, 0},
	{" ->;"," SDM-DAE-INIT   "," -DAE,E", P&reset_dae,			    	  S_INT, 1, P&hid1,	V1, 0, 0},
	{" ->;"," SDM-ARCHIV-STOP"," JA=1  ", P&sdm_arch_stop,		  	US_CHAR, 0, P&hid1,	V0, 0, 0},
	{"*->;"," FerroRAM2 FEHLT","       ", P&ferro_err,			  JANEIN_FORM, 0, P&hid1,	E1, EREIGNIS, 0},
	{"*->;"," SDHC-Card FEHLT","       ", P&card_err,			  JANEIN_FORM, 0, P&hid1,	E1, EREIGNIS, 0},
	{"*->;"," komtab_changed ","       ", P&komtab_changed,			US_INT,  0, P&hid2,	V0, 0, 0},
	{"*->;"," moni_heap_error","       ", P&moni_heap_error,			 US_INT, 0, P&hid2,	V0, 0, 0},
	{" ->;"," test_start     ","       ", P&test_start,			    US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" 89;"," SCHALTPAUSE    "," s     ", P&Schalt_Pause,				US_CHAR, 	0, P&hid1,	V0, 0, 0},
	{" 90;"," PARAM. SICHERN "," JA=1  ", P&bicmove_wunsch,	BICMOVE_FORM, 0, P&hid1,	V0, 0, 0},
	{"*91;"," PROTECTED-VERS.","       ", P&pub_FVers,			 		 DATE_FORM, 0, P&hid2,	V0, 0, 0},
	{"*92;"," PRODUKT-IDF    ","       ", P&Produkt_Idf, 			PROID_FORM, 0, P&hid1,	V0, 0, 0},
	{"*93;"," KATEGORIE-TYP  ","       ", P&Kategorie_Typ,			ASCII_FORM, 0, P&hid2,	V0, 0, 0},
	{"*94;"," KATEGORIE-VERS.","       ", P&Kategorie_Vers,	 	 DATE_FORM, 0, P&hid2,	V0, 0, 0},
	{"*95;"," PROJEKT-TYP    ","       ", P&proj_typ,						 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{"*96;"," PROGRAMM-TYP   ","       ", P&Version_PTyp, 			ASCII_FORM, 0, P&hid1,	V1, 0, 0},
	{"*97;"," PROGR.-VERSION ","       ", P&Version_PVers,			 DATE_FORM, 0, P&hid1,	V1, 0, 0},
	{"*98;"," SYSTEM-VERSION ","       ", P&Version_SVers, 		 DATE_FORM, 0, P&hid1,	V1, 0, 0},
	{" 99;"," KALTSTART      "," JA=1  ", P&Kaltstart,				 KALTST_FORM, 0, P&hid1,	V0, 0, 0},
	{" ->;"," NEUSTART       "," JA=1  ", P&Neustart,					NEUST_FORM, 0, P&hid1,	V0, 0, 0},
} 

const Pgrup dia[] = { 
	{"***:"," DIAGNOSE       ","       ", P&Leer15,							ASCII_FORM, 0, P&hid1,	V1, 0, 0},
	{" 01;"," DIAGNOSE BEGINN","       ", P&dis.begin,		 		 	 DATE_FORM, 1, P&hid1,	V1, 0, 0},
	{" 02;"," DIAGNOSE ENDE  ","       ", P&dis.end, 			 		 	 DATE_FORM, 1, P&hid1,	V1, 0, 0},
	{"*40;"," TVP MAXIMUM    "," C    ", P&did.tvpMax.temp, 				 S_INT, 1, P&hid1,	V1, 0, 0},
	{"*41;"," DATUM TVP MAX  ","       ", P&did.tvpMax.tag,		 	 DATE_FORM, 1, P&hid1,	V1, 0, 0},
	{"*42;"," Ta TVP MAX     "," C    ", P&did.tvpMax.ta,				ANA_FORM, 1, P&hid1,	V1, 0, 0},
	{"*44;"," TVP MINIMUM    "," C    ", P&did.tvpMin.temp, 				 S_INT, 1, P&hid1,	V1, 0, 0},
	{"*45;"," DATUM TVP MIN  ","       ", P&did.tvpMin.tag,		 	 DATE_FORM, 1, P&hid1,	V1, 0, 0},
	{"*46;"," Ta TVP MIN     "," C    ", P&did.tvpMin.ta,				ANA_FORM, 1, P&hid1,	V1, 0, 0},
} 

const Pgrup ze6[] = { 
	{"_**:"," ZAEHLER IN9    ","       ", P&ZE[6],			 				ZE_FORMP, 1,	P&vis,	V1, 0, 0},
	{"*02:"," WAERMEMENGE    "," kWh   ", P&wmengCtr[2].wmeng,	 US_LONG, 0,  P&vis,	V1, 0, 0},
	{"*->:"," VOLUMEN        ","       ", P&ZE[6],			 				ZE_FORMP, 0,  P&vis,	V1, 0, 0},
	{"*->;"," TV-WP          "," C    ", P&wmengCtr[2].pVl,	 ANA_FORMP, 1,  P&hid1,	V0, 0, 0},
	{"*->;"," TR-WP          "," C    ", P&wmengCtr[2].pRl,	 ANA_FORMP, 1,  P&hid1,	V0, 0, 0},
	{" 03;"," KOMMASTELLEN   ","       ", P&ZE[6],							ZE_FORMP, 2,  P&hid1,	V0, 0, 0},
	{" 04;"," DIMENSION      ","       ", P&ZE[6],							ZE_FORMP, 3,  P&hid1,	V0, 0, 0},
	{" 05;"," TEILERFAKTOR   ","       ", P&ZE[6],							ZE_FORMP, 4,  P&hid1,	V0, 0, 0},
	{" 06;"," IMPULSWERT     ","       ", P&ZE[6],							ZE_FORMP, 39, P&hid1,	V0, 0, 0},
	{" ->;"," exponent       ","       ", P&ZE[6],							ZE_FORMP, 36, P&hid2,	V0, 0, 0},
	{" 07;"," ZWISCHENZAEHLER","       ", P&ZE[6],							ZE_FORMP, 8,  P&hid1,	V0, 0, 0},
	{"*08;"," AKT.MON.VOLUM. ","       ", P&ZE[6],							ZE_FORMP, 5,  P&hid1,	V0, 0, 0},
	{"*10:"," JANUAR         "," kWh   ", P&wmengCtr[2].verbr[0],						US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*11:"," FEBRUAR        "," kWh   ", P&wmengCtr[2].verbr[1],				  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*12:"," MAERZ          "," kWh   ", P&wmengCtr[2].verbr[2],				  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*13:"," APRIL          "," kWh   ", P&wmengCtr[2].verbr[3],				  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*14:"," MAI            "," kWh   ", P&wmengCtr[2].verbr[4],				  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*15:"," JUNI           "," kWh   ", P&wmengCtr[2].verbr[5],				  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*16:"," JULI           "," kWh   ", P&wmengCtr[2].verbr[6],				  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*17:"," AUGUST         "," kWh   ", P&wmengCtr[2].verbr[7],				  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*18:"," SEPTEMBER      "," kWh   ", P&wmengCtr[2].verbr[8],				  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*19:"," OKTOBER        "," kWh   ", P&wmengCtr[2].verbr[9],				  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*20:"," NOVEMBER       "," kWh   ", P&wmengCtr[2].verbr[10],			  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*21:"," DEZEMBER       "," kWh   ", P&wmengCtr[2].verbr[11],			  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*22:"," VORJAHR JANUAR "," kWh   ", P&wmengCtr[2].verbr_vj[0],		  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*23:"," VORJAHR FEBRUAR"," kWh   ", P&wmengCtr[2].verbr_vj[1],		  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*24:"," VORJAHR MAERZ  "," kWh   ", P&wmengCtr[2].verbr_vj[2],		  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*25:"," VORJAHR APRIL  "," kWh   ", P&wmengCtr[2].verbr_vj[3],		  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*26:"," VORJAHR MAI    "," kWh   ", P&wmengCtr[2].verbr_vj[4],		  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*27:"," VORJAHR JUNI   "," kWh   ", P&wmengCtr[2].verbr_vj[5],		  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*28:"," VORJAHR JULI   "," kWh   ", P&wmengCtr[2].verbr_vj[6],		  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*29:"," VORJAHR AUGUST "," kWh   ", P&wmengCtr[2].verbr_vj[7],		  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*30:"," VORJAHR SEPT.  "," kWh   ", P&wmengCtr[2].verbr_vj[8],		  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*31:"," VORJAHR OKTOBER"," kWh   ", P&wmengCtr[2].verbr_vj[9],		  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*32:"," VORJAHR NOVEMB."," kWh   ", P&wmengCtr[2].verbr_vj[10],		  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{"*33:"," VORJAHR DEZEMB."," kWh   ", P&wmengCtr[2].verbr_vj[11],		  	US_LONG, 	0, P&vis,  V1, 0 ,0},
	{" 34;"," SYNC.WAERMEMENG"," kWh   ", P&wmengCtr[2].wmeng,							US_LONG,	0, P&hid3, V0, 0, 0},
	{" ->;"," SYNC.JAN       "," kWh   ", P&wmengCtr[2].verbr[0],						US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.FEB       "," kWh   ", P&wmengCtr[2].verbr[1],				  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.MRZ       "," kWh   ", P&wmengCtr[2].verbr[2],				  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.APR       "," kWh   ", P&wmengCtr[2].verbr[3],				  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.MAI       "," kWh   ", P&wmengCtr[2].verbr[4],				  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.JUN       "," kWh   ", P&wmengCtr[2].verbr[5],				  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.JUL       "," kWh   ", P&wmengCtr[2].verbr[6],				  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.AUG       "," kWh   ", P&wmengCtr[2].verbr[7],				  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.SEP       "," kWh   ", P&wmengCtr[2].verbr[8],				  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.OKT       "," kWh   ", P&wmengCtr[2].verbr[9],				  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.NOV       "," kWh   ", P&wmengCtr[2].verbr[10],			  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.DEZ       "," kWh   ", P&wmengCtr[2].verbr[11],			  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.VORJ.JAN  "," kWh   ", P&wmengCtr[2].verbr_vj[0],		  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.VORJ.FEB  "," kWh   ", P&wmengCtr[2].verbr_vj[1],		  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.VORJ.MRZ  "," kWh   ", P&wmengCtr[2].verbr_vj[2],		  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.VORJ.APR  "," kWh   ", P&wmengCtr[2].verbr_vj[3],		  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.VORJ.MAI  "," kWh   ", P&wmengCtr[2].verbr_vj[4],		  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.VORJ.JUN  "," kWh   ", P&wmengCtr[2].verbr_vj[5],		  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.VORJ.JUL  "," kWh   ", P&wmengCtr[2].verbr_vj[6],		  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.VORJ.AUG  "," kWh   ", P&wmengCtr[2].verbr_vj[7],		  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.VORJ.SEP  "," kWh   ", P&wmengCtr[2].verbr_vj[8],		  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.VORJ.OKT  "," kWh   ", P&wmengCtr[2].verbr_vj[9],		  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.VORJ.NOV  "," kWh   ", P&wmengCtr[2].verbr_vj[10],		  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" ->;"," SYNC.VORJ.DEZ  "," kWh   ", P&wmengCtr[2].verbr_vj[11],		  	US_LONG, 	0, P&hid3, V0, 0 ,0},
	{" 35;"," WMZ SYNCHRONIS."," JA=1  ", P&wmengCtr[2].syncFlag,						US_CHAR,	0, P&hid3, V0, 0, 0},
	{" 45;"," MAX LOESCHEN   "," JA=1  ", P&wmengCtr[2].resMax,							US_CHAR,	0, P&hid1, V1, 0, 0},
	{"*46:"," VOLUMENSTROM   "," m/h  ", P&wmengCtr[2].flow,								US_LONG,	1, P&vis,	 V1, 0, 0},
	{"*47:"," LEISTUNG       "," kW    ", P&wmengCtr[2].wmLeistg,						US_INT,		0, P&vis,	 V1, 0, 0},
	{"*48;"," VOLUMENSTR.MAX "," m/h  ", P&wmengCtr[2].flow_max,						US_LONG,	1, P&hid1, V1, 0, 0},
	{"*49;"," LEISTUNG MAX   "," kW    ", P&wmengCtr[2].wmLeistg_max,				US_INT,		0, P&hid1, V1, 0, 0},
	{" 50;"," LEISTG.MITTELN "," min   ", P&MaxLeistung[2].MittelnLeistg, 	US_CHAR,	0, P&hid1, V1, 0, 0},
	{"*51:"," LEI.MITTEL MAX "," kW    ", P&MaxLeistung[2].mittelMax,				US_INT,		0, P&vis,  V1, 0, 0},
	{"*52;"," LEISTG.MITTEL  "," kW    ", P&MaxLeistung[2].mittel,					US_INT,		0, P&hid1, V1, 0, 0},
	{"*53;"," DAT.LEI.MI.MAX ","       ", P&MaxLeistung[2].tag, 		 				DATE_FORM,1, P&hid1, V1, 0, 0},
	{"*54;"," ZEIT LEI.MI.MAX"," h:min ", P&MaxLeistung[2].zeit,		 				ZEIT_FORM,0, P&hid1, V1, 0, 0},
	{"*55;"," Ta LEI.MI.MAX  "," C    ", P&MaxLeistung[2].ta,							ANA_FORM, 1, P&hid1, V1, 0, 0},
	{"*56;"," VL LEI.MI.MAX  "," C    ", P&MaxLeistung[2].vl,							ANA_FORM, 1, P&hid1, V1, 0, 0},
	{"*57;"," RL LEI.MI.MAX  "," C    ", P&MaxLeistung[2].rl,							ANA_FORM, 1, P&hid1, V1, 0, 0},
	{"*58;"," VSTR.LEI.MI.MAX"," m/h  ", P&MaxLeistung[2].flow,						US_LONG,	1, P&hid1, V1, 0, 0},
	{" ->;"," vol.letzter imp"," l     ", P&wmengCtr[2].volumen,						US_INT,	  0, P&hid2, V0, 0, 0},
	{" ->;"," zeit seit imp. "," 200ms ", P&wmengCtr[2].zeitdiff,						US_INT,	  0, P&hid2, V0, 0, 0},
	{" ->;"," zeit letzt.imp."," 200ms ", P&wmengCtr[2].zeitdiffZuletzt,		US_INT,	  0, P&hid2, V0, 0, 0},
	{"*60;"," januar         ","       ", P&ZE[6],			 			ZE_FORMP, 10, P&hid2,	V0, 0, 0},
	{"*61;"," februar        ","       ", P&ZE[6],			 			ZE_FORMP, 11, P&hid2,	V0, 0, 0},
	{"*62;"," maerz          ","       ", P&ZE[6],			 			ZE_FORMP, 12, P&hid2,	V0, 0, 0},
	{"*63;"," april          ","       ", P&ZE[6],			 			ZE_FORMP, 13, P&hid2,	V0, 0, 0},
	{"*64;"," mai            ","       ", P&ZE[6],			 			ZE_FORMP, 14, P&hid2,	V0, 0, 0},
	{"*65;"," juni           ","       ", P&ZE[6],			 			ZE_FORMP, 15, P&hid2,	V0, 0, 0},
	{"*66;"," juli           ","       ", P&ZE[6],			 			ZE_FORMP, 16, P&hid2,	V0, 0, 0},
	{"*67;"," august         ","       ", P&ZE[6],			 			ZE_FORMP, 17, P&hid2,	V0, 0, 0},
	{"*68;"," september      ","       ", P&ZE[6],			 			ZE_FORMP, 18, P&hid2,	V0, 0, 0},
	{"*69;"," oktober        ","       ", P&ZE[6],			 			ZE_FORMP, 19, P&hid2,	V0, 0, 0},
	{"*70;"," november       ","       ", P&ZE[6],			 			ZE_FORMP, 20, P&hid2,	V0, 0, 0},
	{"*71;"," dezember       ","       ", P&ZE[6],			 			ZE_FORMP, 21, P&hid2,	V0, 0, 0},
	{"*72;"," vorjahr januar ","       ", P&ZE[6],			 			ZE_FORMP, 22, P&hid2,	V0, 0, 0},
	{"*73;"," vorjahr februar","       ", P&ZE[6],			 			ZE_FORMP, 23, P&hid2,	V0, 0, 0},
	{"*74;"," vorjahr maerz  ","       ", P&ZE[6],			 			ZE_FORMP, 24, P&hid2,	V0, 0, 0},
	{"*75;"," vorjahr april  ","       ", P&ZE[6],			 			ZE_FORMP, 25, P&hid2,	V0, 0, 0},
	{"*76;"," vorjahr mai    ","       ", P&ZE[6],			 			ZE_FORMP, 26, P&hid2,	V0, 0, 0},
	{"*77;"," vorjahr juni   ","       ", P&ZE[6],			 			ZE_FORMP, 27, P&hid2,	V0, 0, 0},
	{"*78;"," vorjahr juli   ","       ", P&ZE[6],			 			ZE_FORMP, 28, P&hid2,	V0, 0, 0},
	{"*79;"," vorjahr august ","       ", P&ZE[6],			 			ZE_FORMP, 29, P&hid2,	V0, 0, 0},
	{"*80;"," vorjahr sept.  ","       ", P&ZE[6],			 			ZE_FORMP, 30, P&hid2,	V0, 0, 0},
	{"*81;"," vorjahr oktober","       ", P&ZE[6],			 			ZE_FORMP, 31, P&hid2,	V0, 0, 0},
	{"*82;"," vorjahr novemb.","       ", P&ZE[6],			 			ZE_FORMP, 32, P&hid2,	V0, 0, 0},
	{"*83;"," vorjahr dezemb.","       ", P&ZE[6],			 			ZE_FORMP, 33, P&hid2,	V0, 0, 0},
	{" 85:"," sync.zaehlwert ","       ", P&ZE[6],						ZE_FORMP, 6,  P&hid3,	V0, 0, 0},
	{" 86:"," sync.akt.monat ","       ", P&ZE[6],						ZE_FORMP, 7,  P&hid3,	V0, 0, 0},
	{" 87:"," sync.monat 1-24","       ", P&ZE[6],						ZE_FORMP, 9,  P&hid3,	V0, 0, 0},
	{" 88:"," sync.mon.verbr.","       ", P&ZE[6],						ZE_FORMP, 40, P&hid3,	V0, 0, 0},
} 

const Pgrup ze7[] = { 
	{"_**:"," ZAEHLER IN10   ","       ", P&ZE[7],			 				ZE_FORMP, 1,	P&vis,	V1, 0, 0},
	{"*02:"," ZAEHLERWERT    ","       ", P&ZE[7],			 				ZE_FORMP, 0,	P&vis,	V1, 0, 0},
	{" 03;"," KOMMASTELLEN   ","       ", P&ZE[7],			 				ZE_FORMP, 2,	P&hid1,	V0, 0, 0},
	{" 04;"," DIMENSION      ","       ", P&ZE[7],			 				ZE_FORMP, 3,	P&hid1,	V0, 0, 0},
	{" 05;"," TEILERFAKTOR   ","       ", P&ZE[7],			 				ZE_FORMP, 4,	P&hid1,	V0, 0, 0},
	{" 06;"," IMPULSWERT     ","       ", P&ZE[7],							ZE_FORMP, 39,	P&hid1,	V0, 0, 0},
	{" ->;"," exponent       ","       ", P&ZE[7],							ZE_FORMP, 36,	P&hid2,	V0, 0, 0},
	{" 07;"," ZWISCHENZAEHLER","       ", P&ZE[7],							ZE_FORMP, 8,	P&hid1,	V0, 0, 0},
	{"*08;"," AKT.MON.VERBR. ","       ", P&ZE[7],			 				ZE_FORMP, 5,	P&hid1,	V0, 0, 0},
	{"*10:"," JANUAR         ","       ", P&ZE[7],			 				ZE_FORMP, 10, P&vis,	V1, 0, 0},
	{"*11:"," FEBRUAR        ","       ", P&ZE[7],			 				ZE_FORMP, 11, P&vis,	V1, 0, 0},
	{"*12:"," MAERZ          ","       ", P&ZE[7],			 				ZE_FORMP, 12, P&vis,	V1, 0, 0},
	{"*13:"," APRIL          ","       ", P&ZE[7],			 				ZE_FORMP, 13, P&vis,	V1, 0, 0},
	{"*14:"," MAI            ","       ", P&ZE[7],			 				ZE_FORMP, 14, P&vis,	V1, 0, 0},
	{"*15:"," JUNI           ","       ", P&ZE[7],			 				ZE_FORMP, 15, P&vis,	V1, 0, 0},
	{"*16:"," JULI           ","       ", P&ZE[7],			 				ZE_FORMP, 16, P&vis,	V1, 0, 0},
	{"*17:"," AUGUST         ","       ", P&ZE[7],			 				ZE_FORMP, 17, P&vis,	V1, 0, 0},
	{"*18:"," SEPTEMBER      ","       ", P&ZE[7],			 				ZE_FORMP, 18, P&vis,	V1, 0, 0},
	{"*19:"," OKTOBER        ","       ", P&ZE[7],			 				ZE_FORMP, 19, P&vis,	V1, 0, 0},
	{"*20:"," NOVEMBER       ","       ", P&ZE[7],			 				ZE_FORMP, 20, P&vis,	V1, 0, 0},
	{"*21:"," DEZEMBER       ","       ", P&ZE[7],			 				ZE_FORMP, 21, P&vis,	V1, 0, 0},
	{"*22:"," VORJAHR JANUAR ","       ", P&ZE[7],			 				ZE_FORMP, 22, P&vis,	V1, 0, 0},
	{"*23:"," VORJAHR FEBRUAR","       ", P&ZE[7],			 				ZE_FORMP, 23, P&vis,	V1, 0, 0},
	{"*24:"," VORJAHR MAERZ  ","       ", P&ZE[7],			 				ZE_FORMP, 24, P&vis,	V1, 0, 0},
	{"*25:"," VORJAHR APRIL  ","       ", P&ZE[7],			 				ZE_FORMP, 25, P&vis,	V1, 0, 0},
	{"*26:"," VORJAHR MAI    ","       ", P&ZE[7],			 				ZE_FORMP, 26, P&vis,	V1, 0, 0},
	{"*27:"," VORJAHR JUNI   ","       ", P&ZE[7],			 				ZE_FORMP, 27, P&vis,	V1, 0, 0},
	{"*28:"," VORJAHR JULI   ","       ", P&ZE[7],			 				ZE_FORMP, 28, P&vis,	V1, 0, 0},
	{"*29:"," VORJAHR AUGUST ","       ", P&ZE[7],			 				ZE_FORMP, 29, P&vis,	V1, 0, 0},
	{"*30:"," VORJAHR SEPT.  ","       ", P&ZE[7],			 				ZE_FORMP, 30, P&vis,	V1, 0, 0},
	{"*31:"," VORJAHR OKTOBER","       ", P&ZE[7],			 				ZE_FORMP, 31, P&vis,	V1, 0, 0},
	{"*32:"," VORJAHR NOVEMB.","       ", P&ZE[7],			 				ZE_FORMP, 32, P&vis,	V1, 0, 0},
	{"*33:"," VORJAHR DEZEMB.","       ", P&ZE[7],			 				ZE_FORMP, 33, P&vis,	V1, 0, 0},
	{" 34:"," SYNC.ZAEHLWERT ","       ", P&ZE[7],							ZE_FORMP, 6,  P&hid3,	V0, 0, 0},
	{" 35:"," SYNC.AKT.MONAT ","       ", P&ZE[7],							ZE_FORMP, 7,  P&hid3,	V0, 0, 0},
	{" 36:"," SYNC.MONAT 1-24","       ", P&ZE[7],							ZE_FORMP, 9,  P&hid3,	V0, 0, 0},
	{" 37:"," SYNC.MON.VERBR.","       ", P&ZE[7],							ZE_FORMP, 40, P&hid3,	V0, 0, 0},
	{" 38;"," ZAEHLERKONFIG. "," 8...1 ", P&ZE[7],							ZE_FORMP, 34,	P&hid1,	V0, 0, 0},
	{"*39;"," ZAEHLERMEDIUM  ","       ", P&ZE[7],							ZE_FORMP, 38,	P&hid1,	V0, 0, 0},
	{"*40;"," FEHLERSTATUS   "," 8...1 ", P&ZE[7],							ZE_FORMP, 35,	P&hid1,	V0, 0, 0},
	{"_41;"," ZAEHLERNUMMER  ","       ", P&ZE[7], 							ZE_FORMP, 41,	P&hid1,	V1, 0, 0},
	{"*42;"," STICHTAG       ","       ", P&ZE[7],							ZE_FORMP, 37,	P&hid1,	V0, 0, 0},
	{"*43;"," ZAEHLER VORJAHR","       ", P&ZE[7], 							ZE_FORMP, 42,	P&hid1,	V0, 0, 0},
	{" 44;"," SYNC.ZAEHL.VORJ","       ", P&ZE[7], 							ZE_FORMP, 43,	P&hid3,	V0, 0, 0},
} 

const Pgrup dwp[] = { 
	{"***:"," Dimplex-MODBUS ","       ", P&Leer15,																								ASCII_FORM,  0, P&vis,	V0, 0, 0},
	{"*01:"," Aussenlufttemp."," C    ", P&mod_data.i_R_Aussenlufttemperatur, 													  US_INT,  1, P&vis,	V1, 0, 0},
	{"*02:"," Rücklauftemp.  "," C    ", P&mod_data.i_R_Ruecklauftemperatur, 													  US_INT,  1, P&vis,	V1, 0, 0},
	{"*03:"," RL-Solltemp    "," C    ", P&mod_data.i_R_Ruecklaufsolltemperatur, 											  US_INT,  1, P&vis,	V1, 0, 0},
	{"*04:"," Verdichter1-Lz "," h     ", P&mod_data.uc_R_Verdichter1_Stunden, 											     US_CHAR,  0, P&vis,	V1, 0, 0},
	{"*05:"," Verdichter2-Lz "," h     ", P&mod_data.uc_R_Verdichter2_Stunden, 											     US_CHAR,  0, P&vis,	V1, 0, 0},
	{"*06:"," Primaer-PU-Lz  "," h     ", P&mod_data.uc_R_Primaerpumpe_Stunden, 										     US_CHAR,  0, P&vis,	V1, 0, 0},
	{"*07:"," HeizungsPU-Lz  "," h     ", P&mod_data.uc_R_Heizungspumpe_Stunden, 										     US_CHAR,  0, P&vis,	V0, 0, 0},
	{"*08:"," WarmwasserPU-Lz"," h     ", P&mod_data.uc_R_Warmwasserpumpe_Stunden, 									     US_CHAR,  0, P&vis,	V0, 0, 0},
	{" 10:"," Parallelversch ","       ", P&mod_data.uc_W_Parallelverschiebung, 											   US_CHAR,  0, P&vis,	V0, 0, 0},
	{" 11:"," Raumtemperatur "," C    ", P&mod_data.i_W_Raumtemperatur, 															    US_INT,  0, P&vis,	V0, 0, 0},
	{" 12:"," Festsolltempe  "," C    ", P&mod_data.i_W_Festwertsolltemperatur, 										     	US_INT,  0, P&vis,	V1, 0, 0},
	{" 13:"," Heizkurvenendp."," C    ", P&mod_data.i_W_Heizkurvenendpunkt, 										          US_INT,  0, P&vis,	V0, 0, 0},
	{" 14:"," Hysterese IN   "," K     ", P&mod_data.i_W_Hysterese_HK_IN, 									              US_INT,  0, P&vis,	V0, 0, 0},
	{"*15:"," Hysterese OUT  "," K     ", P&mod_data.i_Hysterese_HK_OUT, 									          	    US_INT,  0, P&vis,	V0, 0, 0},
	{" 16:"," Soll dyn. Kuehl"," C    ", P&mod_data.i_W_Solltemp_dyn_Kuehlung, 									        US_INT,  0, P&vis,	V0, 0, 0},
	{" 20:"," Betriebsmodus  ","       ", P&mod_data.uc_W_Betriebsmodus, 											       		 US_CHAR,  0, P&vis,	V1, 0, 0},
	{" 21:"," Partystunden   "," h     ", P&mod_data.uc_W_Anzahl_Partystunden, 											     US_CHAR,  0, P&vis,	V0, 0, 0},
	{" 22:"," Urlaubstage    "," d     ", P&mod_data.uc_W_Anzahl_Urlaubstage, 										       US_CHAR,  0, P&vis,	V0, 0, 0},
	{" 30:"," Hysterese TWE  "," K     ", P&mod_data.i_W_Hysterese_TWE, 											       		 	US_INT,  0, P&vis,	V0, 0, 0},
	{" 31:"," Solltemp. TWE  "," C    ", P&mod_data.i_W_Solltemperatur_TWE, 											        US_INT,  0, P&vis,	V1, 0, 0},
	{"*40:"," Statusmeldung  ","       ", P&mod_data.uc_R_statusmeldung, 											     			 US_CHAR,  0, P&vis,	V1, 0, 0},
	{"*41:"," Sperren        ","       ", P&mod_data.uc_R_WPU_Sperre, 											       			 US_CHAR,  0, P&vis,	V1, 0, 0},
	{"*42:"," Störmeldungen  ","       ", P&mod_data.uc_R_WPU_SM, 										             			 US_CHAR,  0, P&vis,	V1, 0, 0},
	{"*43:"," Sensorik       ","       ", P&mod_data.uc_R_WPU_Sensorik, 										       			 US_CHAR,  0, P&vis,	V1, 0, 0},
	{"*50:"," WW-Thermostat  ","       ", P&mod_data.uc_R_Warmwasserthermostat, 											   US_CHAR,  0, P&vis,	V1, 0, 0},
	{"*51:"," Schw.bad-Therm.","       ", P&mod_data.uc_R_Schwimmbadthermostat, 							    			 US_CHAR,  0, P&vis,	V1, 0, 0},
	{"*52:"," EVU-Sperre     ","       ", P&mod_data.uc_R_EVU_Sperre, 										         			 US_CHAR,  0, P&vis,	V1, 0, 0},
	{"*53:"," Sperre extern  ","       ", P&mod_data.uc_R_Sperre_Extern, 										       			 US_CHAR,  0, P&vis,	V1, 0, 0},
	{"*54:"," Verdichter 1   ","       ", P&mod_data.uc_R_Verdichter1, 											     			 	 US_CHAR,  0, P&vis,	V1, 0, 0},
	{"*55:"," Verdichter 2   ","       ", P&mod_data.uc_R_Verdichter2, 											       			 US_CHAR,  0, P&vis,	V1, 0, 0},
	{"*56:"," Primaer-PU     ","       ", P&mod_data.uc_R_Primaerpumpe, 										             US_CHAR,  0, P&vis,	V0, 0, 0},
	{"*57:"," Heizungs-PU    ","       ", P&mod_data.uc_R_Heizungspumpe, 										       			 US_CHAR,  0, P&vis,	V0, 0, 0},
	{"*58:"," Warmwasser-PU  ","       ", P&mod_data.uc_R_Warmwasserpumpe, 										           US_CHAR,  0, P&vis,	V0, 0, 0},
	{"*59:"," Sammelstoerung ","       ", P&mod_data.uc_R_Sammelstoerung, 										       		 US_CHAR,  0, P&vis,	V1, 0, 0},
	{" 70:"," Stunde         "," 0-23  ", P&mod_data.uc_RW_Stunde_Za, 											     			 	 US_CHAR,  0, P&vis,	V0, 0, 0},
	{" ->:"," set Stunde     "," 0-1   ", P&mod_data.uc_W_setStunde_Za, 										       			 US_CHAR,  0, P&vis,	V0, 0, 0},
	{" 71:"," Minute         "," 0-59  ", P&mod_data.uc_RW_min_Za, 											     			 	 		 US_CHAR,  0, P&vis,	V0, 0, 0},
	{" ->:"," set Minute     "," 0-1   ", P&mod_data.uc_W_setmin_Za, 										       			 		 US_CHAR,  0, P&vis,	V0, 0, 0},
	{" 72:"," Monat          "," 1-12  ", P&mod_data.uc_RW_Monat_Za,  											     			 	 US_CHAR,  0, P&vis,	V0, 0, 0},
	{" ->:"," set Monat      "," 0-1   ", P&mod_data.uc_W_setMonat_Za,  										       			 US_CHAR,  0, P&vis,	V0, 0, 0},
	{" 73:"," Wochentag      "," Mo=1  ", P&mod_data.uc_RW_Wochentag_Za,								     			 	 		 US_CHAR,  0, P&vis,	V0, 0, 0},
	{" ->:"," set Wochentag  "," 0-1   ", P&mod_data.uc_W_setWochentag_Za,							       			 		 US_CHAR,  0, P&vis,	V0, 0, 0},
	{" 74:"," Tag            "," 1-31  ", P&mod_data.uc_RW_Tag_Za,    											     			 	 US_CHAR,  0, P&vis,	V0, 0, 0},
	{" ->:"," set Tag        "," 0-1   ", P&mod_data.uc_W_setTag_Za,    										       			 US_CHAR,  0, P&vis,	V0, 0, 0},
	{" 75:"," Jahr           "," 0-99  ", P&mod_data.uc_RW_Jahr_Za,			      					     			 	 		 US_CHAR,  0, P&vis,	V0, 0, 0},
	{" ->:"," set Jahr       "," 0-1   ", P&mod_data.uc_W_setJahr_Za,					      		       			 		 US_CHAR,  0, P&vis,	V0, 0, 0},
} 

const Pgrup modbusParli[] = { 
	{"***;"," MODBUS         ","       ", P&Leer15,											ASCII_FORM,		0, P&vis,		V0, 0, 0},
	{" 00;"," GERAET         "," # 1-1 ", P&modbusDeviceNr,							EXPAND_CHAR,	0, P&vis,		V0, 0, 0},
	{"*01;"," BEZEICHNUNG    ","       ", P&modbusDevices[0].name,			ASCII_FORM,		0, P&vis,		V0, 0, 0},
	{" 02;"," ADRESSE        ","       ", P&modbusDeviceAddresses[0],			 US_CHAR,		0, P&vis,		V0, 0, 0},
	{"*03;"," R66-SCHNITTST. ","       ", P&modbusDevices[0].sio,		SIO_NAME_FORM,		0, P&vis,		V0, 0, 0},
	{"*03;"," R66-SCHNITTST. ","       ", P&modbusDevices[0].sio,					  S_CHAR,		0, P&hid2,	V0, 0, 0},
	{"*98;"," AKTIVE ZEILE S2","       ", P&activeRow[1],										S_INT,		0, P&vis,		V0, 0, 0},
} 

const Pgrup anl[] = { 
	{"***:"," RIEDEL  R66E   ","       ", P&Kategorie_Typ,				ASCII_FORM, 0, P&vis,		V1, 0, 0},
	{" 01:"," UHRZEIT        ","       ",				0,									UHR_FORM, 0, P&vis,		V1, 0, 0},
	{" 02:"," DATUM          ","       ",				0,								DATUM_FORM, 0, P&vis,		V1, 0, 0},
	{"*03:"," BETRIEBSSTUNDEN"," h     ", P&bst,											US_INT, 0, P&vis,		V1, 0, 0},
	{" ->;"," leerData1      ","       ", P&LeerData[0], 									US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" ->;"," leerSend1      ","       ", P&LeerSend[0], 									S_INT, 0, P&hid2,	V0, 0, 0},
	{"*->;"," Ta 0..10V-Eing."," Volt  ", P&TAE[0],								 ANA_FORMP, 2, P&hid2,	V0, 0, 0},
	{"*->;"," Ta 0..10V-Temp."," C    ", P&ta_ae,									ANA_FORM, 1, P&hid2,	V0, 0, 0},
	{" ->;"," eingabe Ta 0 V "," C    ", P&TaeSkalMin,								 S_INT, 1, P&hid2,	V0, 0, 0},
	{" ->;"," eingabe Ta 10 V"," C    ", P&TaeSkalMax,								 S_INT, 1, P&hid2,	V0, 0, 0},
	{" 12;"," AUSSENLUFTTEMP."," C    ", P&TA[0],								 ANA_FORMP, 1, P&hid2,	V0, 0, 0},
	{" 12:"," AUSSENLUFTTEMP."," C    ", P&ta1m,										ANA_FORM, 1, P&vis,		V1, 0, 0},
	{" 12:"," AUSSENLUFTTEMP."," C    ", P&ta1m,							 	 ANA_FORM, 0x81, P&kom,		E1, FUEHLER, 0},
	{" 13:"," DAEMPFUNGSZEIT "," min   ", P&Ta1mzk,									 US_CHAR, 0, P&vis,		V1, 0, 0},
	{" ->;"," TA-ERSATZ JAN  "," C    ", P&TaErsatz[0],							 S_INT, 1, P&hid1,	V0, 0, 0},
	{" ->;"," TA-ERSATZ FEB  "," C    ", P&TaErsatz[1],							 S_INT, 1, P&hid1,	V0, 0, 0},
	{" ->;"," TA-ERSATZ MRZ  "," C    ", P&TaErsatz[2],							 S_INT, 1, P&hid1,	V0, 0, 0},
	{" ->;"," TA-ERSATZ APR  "," C    ", P&TaErsatz[3],							 S_INT, 1, P&hid1,	V0, 0, 0},
	{" ->;"," TA-ERSATZ MAI  "," C    ", P&TaErsatz[4],							 S_INT, 1, P&hid1,	V0, 0, 0},
	{" ->;"," TA-ERSATZ JUN  "," C    ", P&TaErsatz[5],							 S_INT, 1, P&hid1,	V0, 0, 0},
	{" ->;"," TA-ERSATZ JUL  "," C    ", P&TaErsatz[6],							 S_INT, 1, P&hid1,	V0, 0, 0},
	{" ->;"," TA-ERSATZ AUG  "," C    ", P&TaErsatz[7],							 S_INT, 1, P&hid1,	V0, 0, 0},
	{" ->;"," TA-ERSATZ SEP  "," C    ", P&TaErsatz[8],							 S_INT, 1, P&hid1,	V0, 0, 0},
	{" ->;"," TA-ERSATZ OKT  "," C    ", P&TaErsatz[9],							 S_INT, 1, P&hid1,	V0, 0, 0},
	{" ->;"," TA-ERSATZ NOV  "," C    ", P&TaErsatz[10],							 S_INT, 1, P&hid1,	V0, 0, 0},
	{" ->;"," TA-ERSATZ DEZ  "," C    ", P&TaErsatz[11],							 S_INT, 1, P&hid1,	V0, 0, 0},
	{" ->;"," TA-ERSATZ VERZ."," h     ", P&TaErsatzVerz,						 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ta-ersatz ctr  "," min/2 ", P&TaErsatzCtr,						  US_INT, 0, P&hid2,	V0, 0, 0},
	{"*14:"," AUSSENT. MITTEL"," C    ", P&ta1mh,									ANA_FORM, 1, P&vis,		V1, 0, 0},
	{"*14:"," AUSSENT. MITTEL"," C    ", P&ta1mh,							 ANA_FORM, 0x81, P&kom,		V1, 0, 0},
	{" 15:"," MITTLUNGS-ZEIT "," h     ", P&Ta1mhzk,								 US_CHAR, 0, P&vis,		V1, 0, 0},
	{" 15;"," MITTLUNGS-INIT "," C    ", P&ta1mh_temp,								 S_INT, 1, P&hid1,	V1, 0, 0},
	{" 16:"," Ta-WINTER [EIN]"," C    ", P&Tae,											US_INT, 1, P&vis,		V1, 0, 0},
	{" 17:"," Ta-SOMMER [AUS]"," C    ", P&Taa,											US_INT, 1, P&vis,		V1, 0, 0},
	{"*18:"," SOMMER ?       ","       ", P&sowi,			 					 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
	{" 19:"," PROJEKT-AUSWAHL","       ", P&temp_proj_typ,				   US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" 60:"," SLAVE 1 ADRESSE","       ", P&Slave[0],								 US_CHAR, 0, P&vis,	V0, 0, 0},
	{" ->:"," station1 rxtout"," min   ", P&DM[0].RxTout,			 			 US_CHAR, 0, P&hid2,V0, 0, 0},
	{"*61:"," E: TWE-ANFORD. "," 1=EIN ", P&station1_ea,				 		ANA_FORM, 0, P&vis, 	V0, 0, 0},
	{"+->:"," EINGANG  IN1   ","       ", P&nlist[0],					EA_NAME_FORM, 0, P&vis,		V0, 0, 0},
	{"+->:"," TEXT     IN1   ","       ", P&ntext[0],					 ASCII_FORM, 20, P&vis,		V0, 0, 0},
	{"+->:"," EINGANG  IN2   ","       ", P&nlist[1],					EA_NAME_FORM, 0, P&vis,		V0, 0, 0},
	{"+->:"," TEXT     IN2   ","       ", P&ntext[1],					 ASCII_FORM, 20, P&vis,		V0, 0, 0},
	{"+->:"," EINGANG  IN3   ","       ", P&nlist[2],					EA_NAME_FORM, 0, P&vis,		V0, 0, 0},
	{"+->:"," TEXT     IN3   ","       ", P&ntext[2],					 ASCII_FORM, 20, P&vis,		V0, 0, 0},
	{"+->:"," EINGANG  IN4   ","       ", P&nlist[3],					EA_NAME_FORM, 0, P&vis,		V0, 0, 0},
	{"+->:"," TEXT     IN4   ","       ", P&ntext[3],					 ASCII_FORM, 20, P&vis,		V0, 0, 0},
	{"+->:"," EINGANG  IN5   ","       ", P&nlist[4],					EA_NAME_FORM, 0, P&vis,		V0, 0, 0},
	{"+->:"," TEXT     IN5   ","       ", P&ntext[4],					 ASCII_FORM, 20, P&vis,		V0, 0, 0},
	{"+->:"," EINGANG  IN6   ","       ", P&nlist[5],					EA_NAME_FORM, 0, P&vis,		V0, 0, 0},
	{"+->:"," TEXT     IN6   ","       ", P&ntext[5],					 ASCII_FORM, 20, P&vis,		V0, 0, 0},
	{"+->:"," EINGANG  IN7   ","       ", P&nlist[6],					EA_NAME_FORM, 0, P&vis,		V0, 0, 0},
	{"+->:"," TEXT     IN7   ","       ", P&ntext[6],					 ASCII_FORM, 20, P&vis,		V0, 0, 0},
	{"+->:"," EINGANG  IN8   ","       ", P&nlist[7],					EA_NAME_FORM, 0, P&vis,		V0, 0, 0},
	{"+->:"," TEXT     IN8   ","       ", P&ntext[7],					 ASCII_FORM, 20, P&vis,		V0, 0, 0},
	{"+->:"," EINGANG  IN9   ","       ", P&nlist[8],					EA_NAME_FORM, 0, P&vis,		V0, 0, 0},
	{"+->:"," TEXT     IN9   ","       ", P&ntext[8],					 ASCII_FORM, 20, P&vis,		V0, 0, 0},
	{"+->:"," EINGANG  IN10  ","       ", P&nlist[9],					EA_NAME_FORM, 0, P&vis,		V0, 0, 0},
	{"+->:"," TEXT     IN10  ","       ", P&ntext[9],					 ASCII_FORM, 20, P&vis,		V0, 0, 0},
	{"+->:"," AUSGANG  AA1   ","       ", P&nlist[10],				EA_NAME_FORM, 0, P&vis,		V0, 0, 0},
	{"+->:"," TEXT     AA1   ","       ", P&ntext[10],				 ASCII_FORM, 20, P&vis,		V0, 0, 0},
	{"+->:"," AUSGANG  AA2   ","       ", P&nlist[11],				EA_NAME_FORM, 0, P&vis,		V0, 0, 0},
	{"+->:"," TEXT     AA2   ","       ", P&ntext[11],				 ASCII_FORM, 20, P&vis,		V0, 0, 0},
	{"+->:"," AUSGANG  DA1   ","       ", P&nlist[12],				EA_NAME_FORM, 0, P&vis,		V0, 0, 0},
	{"+->:"," TEXT     DA1   ","       ", P&ntext[12],				 ASCII_FORM, 20, P&vis,		V0, 0, 0},
	{"+->:"," AUSGANG  DA2   ","       ", P&nlist[13],				EA_NAME_FORM, 0, P&vis,		V0, 0, 0},
	{"+->:"," TEXT     DA2   ","       ", P&ntext[13],				 ASCII_FORM, 20, P&vis,		V0, 0, 0},
	{"+->:"," AUSGANG  DA3   ","       ", P&nlist[14],				EA_NAME_FORM, 0, P&vis,		V0, 0, 0},
	{"+->:"," TEXT     DA3   ","       ", P&ntext[14],				 ASCII_FORM, 20, P&vis,		V0, 0, 0},
	{"+->:"," AUSGANG  DA4   ","       ", P&nlist[15],				EA_NAME_FORM, 0, P&vis,		V0, 0, 0},
	{"+->:"," TEXT     DA4   ","       ", P&ntext[15],				 ASCII_FORM, 20, P&vis,		V0, 0, 0},
	{"+->:"," AUSGANG  DA5   ","       ", P&nlist[16],				EA_NAME_FORM, 0, P&vis,		V0, 0, 0},
	{"+->:"," TEXT     DA5   ","       ", P&ntext[16],				 ASCII_FORM, 20, P&vis,		V0, 0, 0},
	{"+->:"," AUSGANG  DA6   ","       ", P&nlist[17],				EA_NAME_FORM, 0, P&vis,		V0, 0, 0},
	{"+->:"," TEXT     DA6   ","       ", P&ntext[17],				 ASCII_FORM, 20, P&vis,		V0, 0, 0},
	{"+->:"," R38_1 EING IN1 ","       ", P&n38list[0][0],				EA_NAME_FORM, 0, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 TEXT IN1 ","       ", P&n38text[0][0],				 ASCII_FORM, 20, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 EING IN2 ","       ", P&n38list[0][1],				EA_NAME_FORM, 0, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 TEXT IN2 ","       ", P&n38text[0][1],				 ASCII_FORM, 20, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 EING IN3 ","       ", P&n38list[0][2],				EA_NAME_FORM, 0, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 TEXT IN3 ","       ", P&n38text[0][2],				 ASCII_FORM, 20, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 EING IN4 ","       ", P&n38list[0][3],				EA_NAME_FORM, 0, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 TEXT IN4 ","       ", P&n38text[0][3],				 ASCII_FORM, 20, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 EING IN5 ","       ", P&n38list[0][4],				EA_NAME_FORM, 0, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 TEXT IN5 ","       ", P&n38text[0][4],				 ASCII_FORM, 20, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 EING IN6 ","       ", P&n38list[0][5],				EA_NAME_FORM, 0, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 TEXT IN6 ","       ", P&n38text[0][5],				 ASCII_FORM, 20, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 EING IN7 ","       ", P&n38list[0][6],				EA_NAME_FORM, 0, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 TEXT IN7 ","       ", P&n38text[0][6],				 ASCII_FORM, 20, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 EING IN8 ","       ", P&n38list[0][7],				EA_NAME_FORM, 0, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 TEXT IN8 ","       ", P&n38text[0][7],				 ASCII_FORM, 20, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 EING IN9 ","       ", P&n38list[0][8],				EA_NAME_FORM, 0, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 TEXT IN9 ","       ", P&n38text[0][8],				 ASCII_FORM, 20, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 EING IN10","       ", P&n38list[0][9],				EA_NAME_FORM, 0, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 TEXT IN10","       ", P&n38text[0][9],				 ASCII_FORM, 20, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 EING IN11","       ", P&n38list[0][10],				EA_NAME_FORM, 0, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 TEXT IN11","       ", P&n38text[0][10],				 ASCII_FORM, 20, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 EING IN12","       ", P&n38list[0][11],				EA_NAME_FORM, 0, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 TEXT IN12","       ", P&n38text[0][11],				 ASCII_FORM, 20, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 EING IN13","       ", P&n38list[0][12],				EA_NAME_FORM, 0, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 TEXT IN13","       ", P&n38text[0][12],				 ASCII_FORM, 20, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 EING IN14","       ", P&n38list[0][13],				EA_NAME_FORM, 0, P&r38vis[0], V0, 0, 0},
	{"+->:"," R38_1 TEXT IN14","       ", P&n38text[0][13],				 ASCII_FORM, 20, P&r38vis[0], V0, 0, 0},
	{"*80:"," SCHALTER HAND ?","       ", P&HardHand,							 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
	{"*81:"," R66 SCHALTER1-6","       ", P&sw_stat_info,						DYN_ASCII_FORM, 6, P&vis,		V1, 0, 0},
	{"*90:"," SMGRUP STANDARD","       ", P&sstm[STANDARD],			 	US_CHAR, 0, P&vis,		A1, GRUP|STANDARD, 0},
	{"*91:"," SMGRUP FUEHLER ","       ", P&sstm[FUEHLER],			 	US_CHAR, 0, P&vis,		A1, GRUP|FUEHLER,  0},
	{"*92:"," SMGRUP MODULE  ","       ", P&sstm[MODULE],			 		US_CHAR, 0, P&vis,		A1, GRUP|MODULE,   0},
	{"*->:"," SSTM ALARME    ","       ", P&sstm_alarme,		 	JANEIN_FORM, 0, P&vis,		V1, 0, 0},
	{"*->:"," SSTM AL+FUEHLER","       ", P&sstm_all,		 			JANEIN_FORM, 0, P&vis,		V1, 0, 0},
	{"*->;"," SSTM RELAIS    ","       ", P&SSTM[ANL],				 JANEIN_FORMOP, 0, P&hid4,	V0, 0, 0},
	{" 98;"," R3X-Simulator  "," EIN=1 ", P&ea_simul,				 				 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" 99;"," serv_count     ","       ", P&serv_cnt,									US_INT, 0, P&hid2,	V0, 0, 0},
	{".99:"," SERVICE-CODE   ","       ", P&service_code,						 US_CHAR, 0, P&vis,		V0, 0, 0},
} 

const Pgrup tes[] = { 
	{"***:"," TEST-ANZEIGEN  ","       ", P&Leer15,						ASCII_FORM, 0, P&hid4,	V0, 0, 0},
	{" 00:"," KomtabKontrolle","       ", P&dae_test,				KOMTEST_FORM, 0, P&hid4,	V0, 0, 0},
	{" ->:"," unbekannt.Alarm"," idx   ", P&unbek_Alarm,			 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{"*01:"," PT_ANIN1       "," Digit ", P&pt_anin[0],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*02:"," PT_ANIN2       "," Digit ", P&pt_anin[1],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*03:"," PT_ANIN3       "," Digit ", P&pt_anin[2],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*04:"," PT_ANIN4       "," Digit ", P&pt_anin[3],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*05:"," PT_ANIN5       "," Digit ", P&pt_anin[4],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*06:"," PT_ANIN6       "," Digit ", P&pt_anin[5],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*07:"," PT_ANIN7       "," Digit ", P&pt_anin[6],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*08:"," PT_ANIN8       "," Digit ", P&pt_anin[7],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*09:"," PT_ANIN_REF1   "," Digit ", P&pt_anin[8],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*10:"," PT_ANIN_REF2   "," Digit ", P&pt_anin[9],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*11:"," ANA_ANIN3      "," Digit ", P&ana_anin[0],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*12:"," ANA_ANIN4      "," Digit ", P&ana_anin[1],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*13:"," ANA_ANIN5      "," Digit ", P&ana_anin[2],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*14:"," ANA_ANIN6      "," Digit ", P&ana_anin[3],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*15:"," ANA_ANIN7      "," Digit ", P&ana_anin[4],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*16:"," ANA_ANIN8      "," Digit ", P&ana_anin[5],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*17:"," ANA_ANIN9      "," Digit ", P&ana_anin[6],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*18:"," ANA_ANIN10     "," Digit ", P&ana_anin[7],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*21:"," DIG_ANIN3      "," Digit ", P&dig_anin[0],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*22:"," DIG_ANIN4      "," Digit ", P&dig_anin[1],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*23:"," DIG_ANIN5      "," Digit ", P&dig_anin[2],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*24:"," DIG_ANIN6      "," Digit ", P&dig_anin[3],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*25:"," DIG_ANIN7      "," Digit ", P&dig_anin[4],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*26:"," DIG_ANIN8      "," Digit ", P&dig_anin[5],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*27:"," DIG_ANIN9      "," Digit ", P&dig_anin[6],				US_INT, 0, P&hid4,	V0, 0, 0},
	{"*28:"," DIG_ANIN10     "," Digit ", P&dig_anin[7],				US_INT, 0, P&hid4,	V0, 0, 0},
	{" 30:"," DE-SIMULATION  "," 1=JA  ", P&de_simul,					US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 31:"," DIG_IN3        ","       ", P&di_mewe[0].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 32:"," DIG_IN4        ","       ", P&di_mewe[1].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 33:"," DIG_IN5        ","       ", P&di_mewe[2].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 34:"," DIG_IN6        ","       ", P&di_mewe[3].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 35:"," DIG_IN7        ","       ", P&di_mewe[4].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 36:"," DIG_IN8        ","       ", P&di_mewe[5].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 37:"," DIG_IN9        ","       ", P&di_mewe[6].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 38:"," DIG_IN10       ","       ", P&di_mewe[7].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 39:"," R37_1 DIG_IN1  ","       ", P&mod37[0].di_mewe[0].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" ->:"," R37_1 DIG_IN2  ","       ", P&mod37[0].di_mewe[1].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" ->:"," R37_1 DIG_IN3  ","       ", P&mod37[0].di_mewe[2].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" ->:"," R37_1 DIG_IN4  ","       ", P&mod37[0].di_mewe[3].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" ->:"," R37_1 DIG_IN5  ","       ", P&mod37[0].di_mewe[4].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" ->:"," R37_1 DIG_IN6  ","       ", P&mod37[0].di_mewe[5].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 40:"," R39_1 DIG_IN1  ","       ", P&mod39[0].di_mewe[0].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" ->:"," R39_1 DIG_IN2  ","       ", P&mod39[0].di_mewe[1].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" ->:"," R39_1 DIG_IN3  ","       ", P&mod39[0].di_mewe[2].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" ->:"," R39_1 DIG_IN4  ","       ", P&mod39[0].di_mewe[3].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" ->:"," R39_1 DIG_IN5  ","       ", P&mod39[0].di_mewe[4].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" ->:"," R39_1 DIG_IN6  ","       ", P&mod39[0].di_mewe[5].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" ->:"," R39_1 DIG_IN7  ","       ", P&mod39[0].di_mewe[6].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" ->:"," R39_1 DIG_IN8  ","       ", P&mod39[0].di_mewe[7].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" ->:"," R39_1 DIG_IN9  ","       ", P&mod39[0].di_mewe[8].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" ->:"," R39_1 DIG_IN10 ","       ", P&mod39[0].di_mewe[9].bwert,	US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" ->:"," R39_1 DIG_IN11 ","       ", P&mod39[0].di_mewe[10].bwert,US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" ->:"," R39_1 DIG_IN12 ","       ", P&mod39[0].di_mewe[11].bwert,US_CHAR, 0, P&hid4,	V0, 0, 0},
	{"*41:"," DIG_OUT1       ","       ", P&Dout[0].wert,		 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{"*42:"," DIG_OUT2       ","       ", P&Dout[1].wert,		 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{"*43:"," DIG_OUT3       ","       ", P&Dout[2].wert,		 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{"*44:"," DIG_OUT4       ","       ", P&Dout[3].wert,		 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{"*45:"," DIG_OUT5       ","       ", P&Dout[4].wert,		 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{"*46:"," DIG_OUT6       ","       ", P&Dout[5].wert,		 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{"*51:"," ANALOG-AUSGANG1"," Digit ", P&anout[0],				 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{"*52:"," ANALOG-AUSGANG2"," Digit ", P&anout[1],				 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{"*61:"," PT-CONTROL     ","       ", P&ptcontrol,			 DIGR_FORM, 8, P&hid4,	V0, 0, 0},
	{"*62:"," AE-CONTROL     ","       ", P&aecontrol,			 DIGR_FORM, 8, P&hid4,	V0, 0, 0},
	{"*63:"," ASW-CONTROL    ","       ", P&aswcontrol,		 DIGR_FORM, 8, P&hid4,	V0, 0, 0},
	{"*64:"," CNT-CONTROL    ","       ", P&cntcontrol,		 DIGR_FORM, 8, P&hid4,	V0, 0, 0},
	{" 65:"," AE-ZERO-CONTROL","       ", P&ae_zero_control,DIGR_FORM, 8, P&hid4,	V0, 0, 0},
	{"[68:"," AKT. LONGZEIT  ","       ", P&LongZeit,		 HEXBUF_FORM, 4, P&hid4,	V0},
	{"[69:"," WRITE TIMESTAMP","       ", P&ulWriteStamp, HEXBUF_FORM, 4, P&hid4,	V0},
	{" 70:"," SOM_BEGIN_MONAT","       ", P&Som_Begin,				 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 71:"," SOM_WOEND      ","       ", P&Som_Woend,				 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 72:"," WIN_BEGIN_MONAT","       ", P&Win_Begin,				 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 73:"," WIN_WOEND      ","       ", P&Win_Woend,				 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 74:"," SWZEIT_MERKER  ","       ", P&swzeit,					 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{"*75:"," LCD-Mode       ","       ", P&pub_LCD_Mode,		 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{"*76:"," FRONT-Status   ","       ", P&front_stat,			 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 77:"," bicmove_flag   ","       ", P&bicmove_flag,		 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 78:"," bicmove_count  ","       ", P&bicmove_count,		 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 79;"," rtc_err_cnt    ","       ", P&rtc_err_cnt,			 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 80;"," noi_sekcnt     "," s     ", P&noi_sekcnt,				US_INT, 0, P&hid4,	V0, 0, 0},
	{" 81;"," noi_us_main_cnt"," s     ", P&noi_user_main_cnt,US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 82;"," noi_mainex     ","       ", P&noi_mainex,				US_INT, 0, P&hid4,	V0, 0, 0},
	{" ->;"," noi_rts_cnt    ","       ", P&noi_rts_cnt,			 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 83;"," spcnt SPEICH   ","       ", P&spcnt,						 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 84;"," sms-anzahl     ","       ", P&sms_anz,					 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 85;"," sms-count      ","       ", P&sms_count,		 		 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{"[86;"," sstm           ","       ", P&sstm[0],			 HEXBUF_FORM, 0, P&hid4,	V0, 0, 0},
	{"[87;"," sstm_old       ","       ", P&sstm_old[0],	 HEXBUF_FORM, 0, P&hid4,	V0, 0, 0},
	{" 88;"," archiv wr-err  ","       ", P&archivWriteError,							US_CHAR,0, P&hid4,	V0, 0, 0},
	{" 89;"," archiv-par rep ","       ", P&archivParRep,			 						US_CHAR,0, P&hid4,	V0, 0, 0},
	{" ->;"," moni_heap_dummy","       ", P&moni_heap_dummy,			 					US_INT, 0, P&hid4,	V0, 0, 0},
	{"*90:"," ZEITMARKE ZEIT ","       ", P&zm_time,										ASCII_FORM, 8, P&hid4,	V0, 0, 0},
	{"*91:"," ZEITMARKE DATUM","       ", P&zm_date,										ASCII_FORM, 8, P&hid4,	V0, 0, 0},
	{"*92:"," S-COMPILE ZEIT ","       ", P&compile_time,							ASCII_FORM, 0, P&hid4,	V0, 0, 0},
	{"*->:"," S-COMPILE DATUM","       ", P&compile_date,							ASCII_FORM, 0, P&hid4,	V0, 0, 0},
	{"*93:"," U-COMPILE ZEIT ","       ", P&user_compile_time,					ASCII_FORM, 0, P&hid4,	V0, 0, 0},
	{"*->:"," U-COMPILE DATUM","       ", P&user_compile_date,					ASCII_FORM, 0, P&hid4,	V0, 0, 0},
	{" 94;"," TRIGPUNKT R5,6k"," %     ", (char *)&Trigpunkt_R56,				 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{"*->;"," TRIGGER R5,6k  ","       ", (char *)&trigger_R56,					  US_INT, 0, P&hid4,	V0, 0, 0},
	{" 95;"," TRIGPUNKT NAMUR"," %     ", (char *)&Trigpunkt_NAMUR,			 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{"*->;"," TRIGGER NAMUR  ","       ", (char *)&trigger_NAMUR,				  US_INT, 0, P&hid4,	V0, 0, 0},
	{" 96;"," TRIGPUNKT KABEL"," %     ", (char *)&Kabelpunkt,						 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{"*->;"," KABELTRIGGER   ","       ", (char *)&kabeltrigger,					  US_INT, 0, P&hid4,	V0, 0, 0},
	{" 97;"," TRIGPUNKT KURZ "," %     ", (char *)&Kurzpunkt,						 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{"*->;"," KURZTRIGGER    ","       ", (char *)&kurztrigger,					  US_INT, 0, P&hid4,	V0, 0, 0},
	{" 98:"," CHAR_TEST1     ","       ", P&char_test1,			 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" 99:"," TP0-9 LOESCHEN ","       ", P&testClear,				 US_CHAR, 0, P&hid4,	V0, 0, 0},
	{" ->;"," TP0            ","       ", P&testPoint[0],			 S_INT, 0, P&hid4,	V0, 0, 0},
	{" ->;"," TP1            ","       ", P&testPoint[1],			 S_INT, 0, P&hid4,	V0, 0, 0},
	{" ->;"," TP2            ","       ", P&testPoint[2],			 S_INT, 0, P&hid4,	V0, 0, 0},
	{" ->;"," TP3            ","       ", P&testPoint[3],			 S_INT, 0, P&hid4,	V0, 0, 0},
	{" ->;"," TP4            ","       ", P&testPoint[4],			 S_INT, 0, P&hid4,	V0, 0, 0},
	{" ->;"," TP5            ","       ", P&testPoint[5],			 S_INT, 0, P&hid4,	V0, 0, 0},
	{" ->;"," TP6            ","       ", P&testPoint[6],			 S_INT, 0, P&hid4,	V0, 0, 0},
	{" ->;"," TP7            ","       ", P&testPoint[7],			 S_INT, 0, P&hid4,	V0, 0, 0},
	{" ->;"," TP8            ","       ", P&testPoint[8],			 S_INT, 0, P&hid4,	V0, 0, 0},
	{" ->;"," TP9            ","       ", P&testPoint[9],			 S_INT, 0, P&hid4,	V0, 0, 0},
} 

const Pgrup zlt[] = { 
	{"***;"," LEITTECHNIK    ","       ", P&Leitstr,										ASCII_FORM, 0, P&hid1,	V0, 0, 0},
	{" 01;"," MODULADRESSE   ","       ", P&ModulAdr,										 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 02;"," MASTER-S1      "," JA=1  ", P&Mode_S1,											 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 03;"," BAUDRATE-S1    "," Baud  ", P&Baudrate_S1,								 BAUD_FORM, 0, P&hid1,	V0, 0, 0},
	{" ->;"," BAUD-S1 QUALI  "," %     ", P&BaudQuali_S1,								   S_INT, 0, P&hid2,	V0, 0, 0},
	{" ->;"," FUNKTION-S1    ","       ", P&Funktion_S1,						  FU_NAME_FORM, 0, P&hid1,	V0, 0, 0},
	{" ->;"," PARITY-S1      ","       ", P&Parity_S1,									   US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," STOPBITS-S1    ","       ", P&Stopbits_S1,								   US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 04;"," MASTER-S2-opto "," JA=1  ", P&Mode_S2,											 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 05;"," BAUDRATE-S2    "," Baud  ", P&Baudrate_S2,								 BAUD_FORM, 0, P&hid1,	V0, 0, 0},
	{" ->;"," BAUD-S2 QUALI  "," %     ", P&BaudQuali_S2,								   S_INT, 0, P&hid2,	V0, 0, 0},
	{" ->;"," FUNKTION-S2    ","       ", P&Funktion_S2,							FU_NAME_FORM, 0, P&hid1,	V0, 0, 0},
	{" ->;"," PARITY-S2      ","       ", P&Parity_S2,									   US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," STOPBITS-S2    ","       ", P&Stopbits_S2,								   US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 06;"," MASTER-S3      "," JA=1  ", P&Mode_S3,											 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 07;"," BAUDRATE-S3    "," Baud  ", P&Baudrate_S3,								 BAUD_FORM, 0, P&hid1,	V0, 0, 0},
	{" ->;"," BAUD-S3 QUALI  "," %     ", P&BaudQuali_S3,								   S_INT, 0, P&hid2,	V0, 0, 0},
	{" ->;"," FUNKTION-S3    ","       ", P&Funktion_S3,							FU_NAME_FORM, 0, P&hid1,	V0, 0, 0},
	{" ->;"," PARITY-S3      ","       ", P&Parity_S3,									   US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," STOPBITS-S3    ","       ", P&Stopbits_S3,								   US_CHAR, 0, P&hid1,	V0, 0, 0},
	{"*->;"," MODULTYP-S3    ","       ", P&spl_kennung,									SPL_FORM, 0, P&hid1,	V0, 0, 0},
	{" ->;"," KENNUNG-S3 SIMU","       ", P&Spl_kennung_simu,						SPL_FORM, 1, P&hid2,	V0, 0, 0},
	{" 08;"," IrDA-S4        "," JA=1  ", P&IrDA_S4,											 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 09;"," MASTER-S4      "," JA=1  ", P&Mode_S4,											 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 10;"," FERNBED  1=GBUS"," 0=XBUS", P&fb_bus,											 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 11;"," FERNBED-ADRESSE","       ", P&fb_adresse,									 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 12;"," FERNBEDIENUNG  "," JA=1  ", P&fernbedien,									 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{"_13;"," OBJ-BEZEICHNUNG","       ", (char*)(OBJBEZ_ADR),		 EEP_ASCII_FORM, 15, P&hid1,	V0, 0, 0},
	{"_14;"," OBJ-NUMMER     ","       ", (char*)(OBJNUM_ADR),		 EEP_ASCII_FORM,  9, P&hid1,	V0, 0, 0},
	{"_15;"," STRASSE        ","       ", (char*)(STRASSE_ADR),	 EEP_ASCII_FORM, 15, P&hid1,	V0, 0, 0},
	{"_16;"," HAUSNUMMER     ","       ", (char*)(NUMMER_ADR),		 EEP_ASCII_FORM,  9, P&hid1,	V0, 0, 0},
	{"_17;"," ORT            ","       ", (char*)(ORT_ADR),		 	 EEP_ASCII_FORM, 15, P&hid1,	V0, 0, 0},
	{"_18;"," PLZ            ","       ", (char*)(PLZAHL_ADR),		 EEP_ASCII_FORM,  9, P&hid1,	V0, 0, 0},
	{"*19;"," OBJ-ORT FEHLT ?","       ", P&ort_idf,									 JANEIN_FORM, 0, P&hid1,	E1, ANZEIGE, 0},
	{"*20;"," STATION-ADRESSE","       ", P&StationsAdr,								 	 US_CHAR, 0, P&hid1,	V1, 0, 0},
	{" ->;"," STATION-INITADR","       ", P&StatInitAdr,									 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{"021;"," MASTER -IDF    ","       ", P&Master_Idf,								 TELE_FORM, 0, P&hid1,	V1, 0, 0},
	{"022;"," STATION-IDF    ","       ", P&Station_Idf,								 TELE_FORM, 0, P&hid1,	V1, 0, 0},
	{"023;"," ALARM-IDF 1    ","       ", P&Alarm_Idf[0],							 TELE_FORM, 0, P&hid1,	V1, 0, 0},
	{"024;"," ALARM-IDF 2    ","       ", P&Alarm_Idf[1],							 TELE_FORM, 0, P&hid1,	V1, 0, 0},
	{"025;"," ALARM-IDF 3    ","       ", P&Alarm_Idf[2],							 TELE_FORM, 0, P&hid1,	V1, 0, 0},
	{"026;"," SERVICE-IDF    ","       ", P&Service_Idf,								 TELE_FORM, 0, P&hid1,	V1, 0, 0},
	{" 27;"," AMTSHOLUNG     "," JA=1  ", P&Amt_hol,									 		 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 28;"," ANRUF-MODUS    ","       ", P&Anrufmodus,							 		 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 29;"," ANRUF-MEDIUM   "," SMS=1 ", P&Anrufmedium,							 		 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 30;"," ANRUF-ANMELDUNG"," JA=1  ", P&anruf_action,						 		 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 31;"," MSN-INIT       "," JA=1  ", P&msnInit,									 		 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{"032;"," PIN-CODE       ","       ", P&PinCode,								 		  PIN_FORM, 4, P&hid1,	V0, 0, 0},
	{"*33;"," PIN FEHLT ?    ","       ", P&pin_fehlt,								 JANEIN_FORM, 0, P&hid1,	E1, ANZEIGE, 0},
	{" 34;"," FELDSTAERKETEST"," JA=1  ", P&csqRequest,									 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{"*35;"," FELDSTAERKEWERT"," >15 OK", P&csqBuf,	 								 		 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{"*36;"," GSM-EINBUCHUNG ","       ", 0,				 								GSM_STATE_FORM, 0, P&hid1,	V0, 0, 0},
	{"*37;"," NETZBETREIBER  ","       ", P&net_name,	 								ASCII_FORM, 0, P&hid1,	V0, 0, 0},
	{" 38;"," MODEM-INIT     "," JA=1  ", P&modem_init,									 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" 39;"," MODEM-NEUSTART "," JA=1  ", P&modem_neustart,							 US_CHAR, 0, P&hid1,	V0, 0, 0},
	{"*40;"," M-STATUS/ACTION","       ", 0,				 									M_STATE_FORM, 0, P&hid1,	V0, 0, 0},
	{" 41;"," MODEM-STATUS   ","       ", P&modem_status,								 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" 42;"," MSTAT-ACTION   ","       ", P&mstat_action,								 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{"*43;"," ALARM-STATUS   ","       ", P&alarm_state,								 DIGR_FORM, 8, P&hid2,	V0, 0, 0},
	{"[44;"," ALARST-EXPAND  ","       ", P&alarm_state_exp[0],			 HEXBUF_FORM, 0, P&hid2,	V0, 0, 0},
	{"*45;"," ANRUF-STATUS   ","       ", P&anruf_state,								 DIGR_FORM, 8, P&hid2,	V0, 0, 0},
	{"*46;"," ANRUF-VERBINDNG","       ", P&dial_state,								 DIGR_FORM, 8, P&hid2,	V0, 0, 0},
	{" 47;"," ANRUF-PAUSE-CNT"," min   ", P&anrufpause,						 			  US_INT, 0, P&hid2,	V0, 0, 0},
	{" 48;"," STANDARD-PAUSE "," min   ", P&Standpause,						 			  US_INT, 0, P&hid2,	V0, 0, 0},
	{" 49;"," ANRUF-EXTRA    "," JA=1  ", P&anruf_extra,				  		 		 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" 50;"," ZLT-DIREKT     "," JA=1  ", P&Zlt_direkt,									 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" 51;"," DLB-FUNKTION   "," JA=1  ", P&DlbFunktion,									 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" 52;"," DC1-Protokoll  "," JA=1  ", P&dc1_prot,										 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" 53;"," DC1-Enable     "," JA=1  ", P&dc1_enable,									 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{"[60;"," TXBUF_LP       ","       ", P&TxBuf_LP[0],							 HEXBUF_FORM, 8, P&hid2,	V0, 0, 0},
	{"[61;"," RXBUF_LP       ","       ", P&RxBuf_LP[0],							 HEXBUF_FORM, 8, P&hid2,	V0, 0, 0},
	{"[62;"," TXBUF_IFU      ","       ", P&TxBuf_IFU[0],						 HEXBUF_FORM, 8, P&hid2,	V0, 0, 0},
	{"[63;"," RXBUF_IFU      ","       ", P&RxBuf_IFU[0],						 HEXBUF_FORM, 8, P&hid2,	V0, 0, 0},
	{"[64;"," TXBUF_S1       ","       ", P&TxBuf_S1[0],							 HEXBUF_FORM, 8, P&hid2,	V0, 0, 0},
	{"[65;"," RXBUF_S1       ","       ", P&RxBuf_S1[0],							 HEXBUF_FORM, 8, P&hid2,	V0, 0, 0},
	{"[66;"," TXBUF_S2       ","       ", P&TxBuf_S2[0],							 HEXBUF_FORM, 8, P&hid2,	V0, 0, 0},
	{"[67;"," RXBUF_S2       ","       ", P&RxBuf_S2[0],							 HEXBUF_FORM, 8, P&hid2,	V0, 0, 0},
	{"[68;"," TXBUF_S3       ","       ", P&TxBuf_S3[0],							 HEXBUF_FORM, 8, P&hid2,	V0, 0, 0},
	{"[69;"," RXBUF_S3       ","       ", P&RxBuf_S3[0],							 HEXBUF_FORM, 8, P&hid2,	V0, 0, 0},
	{"[68;"," TXBUF_S4       ","       ", P&TxBuf_IR[0],							 HEXBUF_FORM, 8, P&hid2,	V0, 0, 0},
	{"[69;"," RXBUF_S4       ","       ", P&RxBuf_IR[0],							 HEXBUF_FORM, 8, P&hid2,	V0, 0, 0},
	{" 70;"," RX_TEST-S1     ","       ", P&rxtest_S1,										 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" 71;"," RX_TEST-S2     ","       ", P&rxtest_S2,										 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" 72;"," RX_TEST-S3     ","       ", P&rxtest_S3,										 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" 72;"," RX_TEST-S4     ","       ", P&rxtest_S4,										 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" 73;"," RX_TEST-LP     ","       ", P&rxtest_LP,										 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" 74;"," STATUS-S1      ","       ", P&status_S1,										 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" 75;"," STATUS-S2      ","       ", P&status_S2,										 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" 76;"," STATUS-S3      ","       ", P&status_S3,										 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" 76;"," STATUS-S4      ","       ", P&status_S4,										 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" 77;"," INAKTIV-CNT    ","       ", P&inactiv_cnt,										US_INT, 0, P&hid2,	V0, 0, 0},
	{" 78;"," RX-TIMER       ","       ", P&rxtimer,												US_INT, 0, P&hid2,	V0, 0, 0},
	{" 79;"," M-TIMER        ","       ", P&mtimer,												US_INT, 0, P&hid2,	V0, 0, 0},
	{" 80;"," DIAL-TIMER     "," sek   ", P&dial_timer,									 US_LONG, 1, P&hid2,	V0, 0, 0},
	{"[81;"," DIAL-ERROR-CNT ","       ", P&dial_errcount,						 HEXBUF_FORM, 3, P&hid2,	V0, 0, 0},
	{"[82;"," DIAL-TRY       ","       ", P&dial_try,								 HEXBUF_FORM, 3, P&hid2,	V0, 0, 0},
	{" 83;"," COMMAND-TIO-CNT","       ", P&command_tio_cnt,								US_INT, 0, P&hid2,	V0, 0, 0},
	{"*90:"," GPRS-STATUS    ","       ", P&gprs_connection.ucf_status_ascii[0],		 		ASCII_FORM,  15, 	P&hid1,		V0, 0, 0},
	{" 91:"," USE GPRS       "," JA=1  ", P&uc_use_gprs,																US_CHAR, 			0, 	P&hid1,		V0, 0, 0},
	{" 92:"," RECONNECT GPRS "," ***   ", P&uc_gprs_reconnect,													US_CHAR, 			0, 	P&hid1,		V0, 0, 0},
	{"_93:"," APN 1          ","       ", P&gprs_connection.ucf_apn[0],		 						ASCII_FORM,  15, 	P&hid1,		V0, 0, 0},
	{"_94:"," APN 2          ","       ", P&gprs_connection.ucf_apn[15],		 						ASCII_FORM,  15, 	P&hid1,		V0, 0, 0},
	{"_95:"," MAIN ADDRESS 1 ","       ", P&gprs_connection.ucf_main_address[0],		 		ASCII_FORM,  15, 	P&hid1,		V0, 0, 0},
	{"_96:"," MAIN ADDRESS 2 ","       ", P&gprs_connection.ucf_main_address[15],		 	ASCII_FORM,  15, 	P&hid1,		V0, 0, 0},
	{"_97:"," MAIN ADDRESS 3 ","       ", P&gprs_connection.ucf_main_address[30],		 	ASCII_FORM,  15, 	P&hid1,		V0, 0, 0},
	{"*->;"," curr address 1 ","       ", P&gprs_connection.ucf_current_address[0],		ASCII_FORM,  15, 	P&hid2,		V0, 0, 0},
	{"*->;"," curr address 2 ","       ", P&gprs_connection.ucf_current_address[15],		ASCII_FORM,  15, 	P&hid2,		V0, 0, 0},
	{"*->;"," curr address 3 ","       ", P&gprs_connection.ucf_current_address[30],		ASCII_FORM,  15, 	P&hid2,		V0, 0, 0},
} 

const Pgrup alk[] = { 
	{"***;"," ALARMKONTROLLE ","       ", P&Leer15,										ASCII_FORM, 0, P&hid3,	V0, 0, 0},
	{" 00:"," PARAM. SICHERN "," 1=JA  ", P&altest_speich,								 US_CHAR, 0, P&hid3,	V0, 0, 0},
	{" 01:"," ALARM-NUMMER   "," # 0-  ", P&alarm_test,						ALARMTEST_FORM, 0, P&hid3,	V0, 0, 0},
	{" 01:"," AlarmKontrolle ","       ", P&alarm_test,						ALARMTEST_FORM, 1, P&hid3,	V0, 0, 0},
	{" 02:"," AKTIVIERUNG    "," s     ", P&alarmtab[0].Waitlimit,	ALARMTEST_FORM, 2, P&hid3,	V0, 0, 0},
	{" 03:"," MASKE          ","       ", P&alarmtab[0].Maske,			ALARMTEST_FORM, 3, P&hid3,	V0, 0, 0},
	{" 04:"," LED-FUNKTION   ","       ", P&alarmtab[0].Ledfunc,		ALARMTEST_FORM, 4, P&hid3,	V0, 0, 0},
	{" 05:"," LCD-ANZEIGE    "," s     ", P&alarmtab[0].Visloader,	ALARMTEST_FORM, 5, P&hid3,	V0, 0, 0},
} 

const Pgrup hk1[] = { 
	{"_**:"," HEIZKREIS 1    ","       ", P&hkd[HK1].raumname,	ASCII_FORM, 0, P&vis,		V1, 0, 0},
	{"*01:"," VORLAUF   IST  "," C    ", P&TVS[HK1],						 ANA_FORMP, 1, P&vis,		V1, 0, 0},
	{"*01:"," VORLAUF   IST  "," C    ", P&TVS[HK1],					ANA_FORMP, 0x81, P&kom,		E1, FUEHLER, 0},
	{" 04:"," raum-ext. ist  "," C    ", P&hkd[HK1].tibed,					 S_INT, 1, P&hid2,	V0, 0, 0},
	{" 06;"," SO/WI HK-EXTRA "," 1=JA  ", P&hks[HK1].SoWiExtra,		 US_CHAR, 0, P&hid1,	V1, 0, 0},
	{" 07;"," Ta-WINTER [EIN]"," C    ", P&hks[HK1].Tae,						US_INT, 1, P&hid1,	V1, 0, 0},
	{" 08;"," Ta-SOMMER [AUS]"," C    ", P&hks[HK1].Taa,						US_INT, 1, P&hid1,	V1, 0, 0},
	{"*09;"," SOMMER ?       ","       ", P&hkd[HK1].sowi,		 JANEIN_FORM, 0, P&hid1,	V1, 0, 0},
	{" 10:"," STEIGUNG       ","       ", P&hks[HK1].Anst,					US_INT, 2, P&vis,		V1, 0, 0},
	{" 11:"," NIVEAU         "," C    ", P&hks[HK1].Tvpa,					US_INT, 1, P&vis,		V1, 0, 0},
	{" 12:"," VORLAUF   MAX  "," C    ", P&hks[HK1].Tvma,					US_INT, 1, P&vis,		V1, 0, 0},
	{" 13:"," VORLAUF   MIN  "," C    ", P&hks[HK1].Tvmi,					US_INT, 1, P&vis,		V1, 0, 0},
	{" 14:"," raum      soll "," C    ", P&hks[HK1].Tiso,					US_INT, 1, P&hid2,	V0, 0, 0},
	{" 14:"," raum-ext. soll "," C    ", P&hkd[HK1].tisobed,				US_INT, 1, P&hid2,	V0, 0, 0},
	{" 15:"," raum      min  "," C    ", P&hks[HK1].Timi,					US_INT, 1, P&hid2,	V0, 0, 0},
	{" ->;"," raum min hyst. "," K     ", P&hks[HK1].TimiHyst,			US_INT, 1, P&hid2,	V0, 0, 0},
	{" 16;"," kask.soll max  "," C    ", P&hks[HK1].KaskBegr,			US_INT, 1, P&hid2,	V0, 0, 0},
	{" 17;"," xp-raum kaskade","       ", P&hks[HK1].Kpk,						US_INT, 2, P&hid2,	V0, 0, 0},
	{"*20:"," VORLAUF BERECHN"," C    ", P&hkd[HK1].tvsb,					US_INT, 1, P&vis,		V1, 0, 0},
	{"*->:"," vorlauf ber.hkl"," C    ", P&hkd[HK1].tvsb_hkl,			US_INT, 1, P&hid2,	V0, 0, 0},
	{"*->:"," korrektur adapt"," K     ", P&hkd[HK1].adaptKorr,			 S_INT, 1, P&hid2,	V0, 0, 0},
	{"*->:"," korrektur kaska"," K     ", P&hkd[HK1].kaskaKorr,			 S_INT, 1, P&hid2,	V0, 0, 0},
	{"*->:"," korrektur wwvor"," K     ", P&hkd[HK1].wwvorKorr,			 S_INT, 1, P&hid2,	V0, 0, 0},
	{" ->:"," vorlauf filt.zk"," s     ", P&hks[HK1].Fzk,						US_INT, 1, P&hid2,	V0, 0, 0},
	{" 25;"," ESTR.-PR.START ","       ", P&hks[HK1].StartAufheiz, DATE_FORM, 1, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG1 "," C    ", P&hks[HK1].EstrichTemp[0], US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG2 "," C    ", P&hks[HK1].EstrichTemp[1], US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG3 "," C    ", P&hks[HK1].EstrichTemp[2], US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG4 "," C    ", P&hks[HK1].EstrichTemp[3], US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG5 "," C    ", P&hks[HK1].EstrichTemp[4], US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG6 "," C    ", P&hks[HK1].EstrichTemp[5], US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG7 "," C    ", P&hks[HK1].EstrichTemp[6], US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG8 "," C    ", P&hks[HK1].EstrichTemp[7], US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG9 "," C    ", P&hks[HK1].EstrichTemp[8], US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG10"," C    ", P&hks[HK1].EstrichTemp[9], US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG11"," C    ", P&hks[HK1].EstrichTemp[10],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG12"," C    ", P&hks[HK1].EstrichTemp[11],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG13"," C    ", P&hks[HK1].EstrichTemp[12],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG14"," C    ", P&hks[HK1].EstrichTemp[13],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG15"," C    ", P&hks[HK1].EstrichTemp[14],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG16"," C    ", P&hks[HK1].EstrichTemp[15],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG17"," C    ", P&hks[HK1].EstrichTemp[16],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG18"," C    ", P&hks[HK1].EstrichTemp[17],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG19"," C    ", P&hks[HK1].EstrichTemp[18],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG20"," C    ", P&hks[HK1].EstrichTemp[19],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG21"," C    ", P&hks[HK1].EstrichTemp[20],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG22"," C    ", P&hks[HK1].EstrichTemp[21],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG23"," C    ", P&hks[HK1].EstrichTemp[22],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG24"," C    ", P&hks[HK1].EstrichTemp[23],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG25"," C    ", P&hks[HK1].EstrichTemp[24],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG26"," C    ", P&hks[HK1].EstrichTemp[25],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG27"," C    ", P&hks[HK1].EstrichTemp[26],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG28"," C    ", P&hks[HK1].EstrichTemp[27],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG29"," C    ", P&hks[HK1].EstrichTemp[28],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{" ->;"," ESTR.TEMP.TAG30"," C    ", P&hks[HK1].EstrichTemp[29],US_CHAR, 0, P&hid1,	V0, 0, 0},
	{"*26:"," ESTRICH-PROGR.?","       ", P&hkd[HK1].estrichProg,JANEIN_FORM, 0, P&vis, 	E1, STANDARD, 0},
	{"*27;"," ESTRICH AKT.TAG","       ", P&hkd[HK1].estrichTag,		 US_CHAR, 0, P&hid1,	V1, 0, 0},
	{"*27;"," ESTR.AKT.SOLLT."," C    ", P&hkd[HK1].estrichTemp,			US_INT, 0, P&hid1,	V0, 0, 0},
	{" 28:"," ANFORD.ANHEBUNG"," K     ", P&hks[HK1].TvpAnh,				US_INT, 1, P&vis,			V1, 0, 0},
	{" 30:"," ABSENK-BEGIN WO"," h:min ", P&abs_tab[HK1][0].begin,ZEIT_FORM,0, P&vis,		V1, 0, 0},
	{" 31:"," ABSENK-DAUER WO"," h     ", P&abs_tab[HK1][0].dauer, US_CHAR, 0, P&vis,		V1, 0, 0},
	{" 32:"," ABSENK-WERT  WO"," K     ", P&abs_tab[HK1][0].abwert,	US_INT, 1, P&vis,		V1, 0, 0},
	{" 34:"," GANZE WOCHE SET"," 1=JA  ", P&setwoche[HK1],				 US_CHAR, 0, P&vis,		V1, 0, 0},
	{" 35:"," ABSENK-BEGIN Mo"," h:min ", P&abs_tab[HK1][1].begin,ZEIT_FORM,0, P&vis,		V1, 0, 0},
	{" ->:"," ABSENK-DAUER Mo"," h     ", P&abs_tab[HK1][1].dauer, US_CHAR, 0, P&vis,		V1, 0, 0},
	{" ->:"," ABSENK-WERT  Mo"," K     ", P&abs_tab[HK1][1].abwert,	US_INT, 1, P&vis,		V1, 0, 0},
	{" 36:"," ABSENK-BEGIN Di"," h:min ", P&abs_tab[HK1][2].begin,ZEIT_FORM,0, P&vis,		V1, 0, 0},
	{" ->:"," ABSENK-DAUER Di"," h     ", P&abs_tab[HK1][2].dauer, US_CHAR, 0, P&vis,		V1, 0, 0},
	{" ->:"," ABSENK-WERT  Di"," K     ", P&abs_tab[HK1][2].abwert,	US_INT, 1, P&vis,		V1, 0, 0},
	{" 37:"," ABSENK-BEGIN Mi"," h:min ", P&abs_tab[HK1][3].begin,ZEIT_FORM,0, P&vis,		V1, 0, 0},
	{" ->:"," ABSENK-DAUER Mi"," h     ", P&abs_tab[HK1][3].dauer, US_CHAR, 0, P&vis,		V1, 0, 0},
	{" ->:"," ABSENK-WERT  Mi"," K     ", P&abs_tab[HK1][3].abwert,	US_INT, 1, P&vis,		V1, 0, 0},
	{" 38:"," ABSENK-BEGIN Do"," h:min ", P&abs_tab[HK1][4].begin,ZEIT_FORM,0, P&vis,		V1, 0, 0},
	{" ->:"," ABSENK-DAUER Do"," h     ", P&abs_tab[HK1][4].dauer, US_CHAR, 0, P&vis,		V1, 0, 0},
	{" ->:"," ABSENK-WERT  Do"," K     ", P&abs_tab[HK1][4].abwert,	US_INT, 1, P&vis,		V1, 0, 0},
	{" 39:"," ABSENK-BEGIN Fr"," h:min ", P&abs_tab[HK1][5].begin,ZEIT_FORM,0, P&vis,		V1, 0, 0},
	{" ->:"," ABSENK-DAUER Fr"," h     ", P&abs_tab[HK1][5].dauer, US_CHAR, 0, P&vis,		V1, 0, 0},
	{" ->:"," ABSENK-WERT  Fr"," K     ", P&abs_tab[HK1][5].abwert,	US_INT, 1, P&vis,		V1, 0, 0},
	{" 40:"," ABSENK-BEGIN Sa"," h:min ", P&abs_tab[HK1][6].begin,ZEIT_FORM,0, P&vis,		V1, 0, 0},
	{" ->:"," ABSENK-DAUER Sa"," h     ", P&abs_tab[HK1][6].dauer, US_CHAR, 0, P&vis,		V1, 0, 0},
	{" ->:"," ABSENK-WERT  Sa"," K     ", P&abs_tab[HK1][6].abwert,	US_INT, 1, P&vis,		V1, 0, 0},
	{" 41:"," ABSENK-BEGIN So"," h:min ", P&abs_tab[HK1][7].begin,ZEIT_FORM,0, P&vis,		V1, 0, 0},
	{" ->:"," ABSENK-DAUER So"," h     ", P&abs_tab[HK1][7].dauer, US_CHAR, 0, P&vis,		V1, 0, 0},
	{" ->:"," ABSENK-WERT  So"," K     ", P&abs_tab[HK1][7].abwert,	US_INT, 1, P&vis,		V1, 0, 0},
	{"*->;"," ZEITABSENKPHASE","       ", P&abs_ram[HK1].absen,	 JANEIN_FORM, 0, P&hid1,V1, 0, 0},
	{" ->;"," bedarfs-absenk."," K     ", P&hks[HK1].Beabs,					US_INT, 1, P&hid2,	V0, 0, 0},
	{" 50:"," HEIZ-TaGRENZE  "," C    ", P&hks[HK1].TaHeizgrenze,		 S_INT, 1, P&vis,	V1, 0, 0},
	{" 51:"," FROST-TaGRENZE "," C    ", P&hks[HK1].TaFrostgrenze,		 S_INT, 1, P&vis,	V1, 0, 0},
	{" 52:"," ABSCH-ZEITKONST"," h/K   ", P&hks[HK1].AbschZeitKonst,	US_INT, 1, P&vis,	V1, 0, 0},
	{" ->;"," vl max sommer  "," C    ", P&hks[HK1].VorlaufMaxSommer, US_INT, 1, P&hid2,	V0, 0, 0},
	{" 60:"," SCHNELLAUFHEIZ."," JA=1  ", P&hks[HK1].Sauf,				 US_CHAR, 0, P&vis,		V1, 0, 0},
	{" 61:"," SO/WI-AUTOMATIK"," JA=1  ", P&hks[HK1].Swhk,				 US_CHAR, 0, P&vis,		V1, 0, 0},
	{" 68;"," TDIFF.ALARM EIN"," K     ", P&hks[HK1].TabwMax,			 US_CHAR, 1, P&hid1,	V1, 0, 0},
	{" 69;"," ZVERZ.ALARM EIN"," min   ", P&hks[HK1].TabwZeit,		 US_CHAR, 0, P&hid1,	V1, 0, 0},
	{" ->:"," bedarf         "," 1J 2N ", P&hkd[HK1].bedarf,	 		 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" ->:"," vorheiz_bed    ","       ", P&hkd[HK1].vorheiz_bed,	 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" ->:"," ticopy         ","       ", P&hkd[HK1].ticopy,			 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" ->:"," CountDown      ","       ", P&hkd[HK1].CountDown,  	 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{" ->;"," vorrang bedarf ","       ", P&hkd[HK1].vorra_bed,		 US_CHAR, 0, P&hid2,	V0, 0, 0},
	{"*70:"," WPU-HEIZEN ?   ","       ", P&wpd[WP1].chPa_WPU_HEI, 		 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
	{"*71:"," WPU-TWE ?      ","       ", P&wpd[WP1].chPa_WPU_TWE, 		 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
	{"*72:"," HEIZ-PUMPE EIN?","       ", P&PU[HK1], 				 JANEIN_FORMOP, 0, P&vis,		V1, 0, 0},
	{"*73;"," PUMPEN-LAUFZEIT"," h     ", P&hkd[HK1].puLz,					US_INT, 0, P&hid1,	V1, 0, 0},
	{"*74:"," BM HEIZ-PU EIN?","       ", P&BMPU[HK1], 			 JANEIN_FORMIP, 0, P&vis,		V1, 0, 0},
	{" 74;"," WARTEN BM PUMPE"," min   ", P&hks[HK1].PuBmVerz,		 US_CHAR, 0, P&hid1,	V1, 0, 0},
	{" ->:"," puBmVerz Ctr   "," min/2 ", P&hkd[HK1].puBmVerz,		  US_INT, 0, P&hid2,	V0, 0, 0},
	{" 76;"," PU-NACHLAUFZEIT"," min   ", P&hks[HK1].Puna,					US_CHAR, 0, P&hid1,	V1, 0, 0},
	{" ->;"," pu-nachlauf cnt"," min/2 ", P&hkd[HK1].zpu,						 US_INT, 0, P&hid2,	V0, 0, 0},
	{"*80:"," BETRIEBS-REGIE ","       ", P&hkd[HK1].regie_txt, DYN_ASCII_FORM, 0, P&vis,		V1, 0, 0},
	{"*81:"," ABSENKPHASE ?  ","       ", P&hkd[HK1].absen,		 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
	{"*->:"," ABSCHALTPHASE ?","       ", P&hkd[HK1].absch,		 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
	{"*->:"," FROSTBETRIEB ? ","       ", P&hkd[HK1].frost,		 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
	{"*82:"," AUFHEIZPHASE ? ","       ", P&hkd[HK1].aufhe,		 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
	{"*83:"," SOMMERBETRIEB ?","       ", P&hkd[HK1].somme,	 	 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
	{" ->:"," absenkwert abs "," K     ", P&abs_ram[HK1].tvab,			US_INT, 1, P&hid2,	V0, 0, 0},
	{" ->:"," absenkzeit abs "," s/10  ", P&abs_ram[HK1].zasd,			US_INT, 0, P&hid2,	V0, 0, 0},
	{" ->:"," abschalt   abs "," s/10  ", P&abs_ram[HK1].zAbsch,		US_INT, 0, P&hid2,	V0, 0, 0},
	{" ->:"," aufheiz    abs "," s/10  ", P&abs_ram[HK1].zahd,			US_INT, 0, P&hid2,	V0, 0, 0},
	{" ->:"," absenkwert bed "," K     ", P&abs_bed[HK1].tvab,			US_INT, 1, P&hid2,	V0, 0, 0},
	{" ->:"," absenkzeit bed "," s/10  ", P&abs_bed[HK1].zasd,			US_INT, 0, P&hid2,	V0, 0, 0},
	{" ->:"," abschalt   bed "," s/10  ", P&abs_bed[HK1].zAbsch,		US_INT, 0, P&hid2,	V0, 0, 0},
	{" ->:"," aufheiz    bed "," s/10  ", P&abs_bed[HK1].zahd,			US_INT, 0, P&hid2,	V0, 0, 0},
	{" ->:"," ww-vorrang ?   ","       ", P&hkd[HK1].vorra,	 	 JANEIN_FORM, 0, P&hid2,	V0, 0, 0},
	{"*86:"," SM REGELABW.?  ","       ", P&hkd[HK1].abwAlarm, JANEIN_FORM, 0, P&vis, 	A1, EINZEL,   0},
	{"*87:"," SM STW ?       ","       ", P&STWHK[HK1], 		 JANEIN_FORMIP, 0, P&vis,		A1, EINZEL,   0},
	{"*88:"," SM BM-HEIZ-PU ?","       ", P&hkd[HK1].puBm,	 	JANEIN_FORM, 0, P&vis,		E1, STANDARD, 0},
	{"*89:"," HANDBETRIEB ?  ","       ", P&hks[HK1].Haut,		 JANEIN_FORM, 0, P&vis,		E1, EREIGNIS, 0},
	{" 90;"," P-VERSTAERKUNG "," %/K   ", P&hks[HK1].Kp,						US_INT, 2, P&hid1,	V1, 0, 0},
	{" 91;"," D-VERSTAERKUNG ","       ", P&hks[HK1].Kd,						US_INT, 2, P&hid1,	V1, 0, 0},
	{" 92;"," TASTZEIT       "," s     ", P&hks[HK1].Ts,						US_INT, 1, P&hid1,	V1, 0, 0},
	{" 93;"," NACHSTELLZEIT  "," s     ", P&hks[HK1].Tn,						US_INT, 1, P&hid1,	V1, 0, 0},
	{" 94;"," VENTILSTELL.MIN"," %     ", P&hks[HK1].Y_rel_min,	 		US_INT, 1, P&hid1,	V1, 0, 0},
	{" 95;"," OEFFNUNGSBEGINN"," %     ", P&hks[HK1].Y_rel_beg,	 		US_INT, 1, P&hid1,	V1, 0, 0},
	{"*96;"," SOLLWERT       "," C    ", P&hkd[HK1].tsol,					US_INT, 1, P&hid1,	V1, 0, 0},
	{"*97;"," REGELABWEICHUNG"," K     ", P&hkd[HK1].ei,						 S_INT, 1, P&hid1,	V1, 0, 0},
	{"*->;"," dy_rel         ","       ", P&hkd[HK1].dy_rel,				 S_INT, 3, P&hid2,	V0, 0, 0},
	{"*98;"," VENTILSTELLUNG "," %     ", P&RVENT[HK1],					AOUT_FORMP, 1, P&hid1,	V1, 0, 0},
	{"*->;"," pid-stellgroess"," %     ", P&hkd[HK1].si_y_rel,			 S_INT, 1, P&hid2,	V0, 0, 0},
	{" ->;"," pid-windup     "," %     ", P&hks[HK1].Wup,			 			US_INT, 1, P&hid2,	V0, 0, 0},
	{" 99;"," HAND/AUTOMATIK "," HAND=1", P&hks[HK1].Haut,				 US_CHAR, 0, P&hid1,	V1, 0, 0},
	{" ->:"," PUMPE EIN/AUS  "," EIN=1 ", P&hks[HK1].Puea,		 		 US_CHAR, 0, P&hid1,	V1, 0, 0},
	{" ->:"," VENTIL STELLEN "," %     ", P&hks[HK1].Vstell,			  US_INT, 1, P&hid1,	V1, 0, 0},
} 

const Parli Pgruppe[] = { 
	{"ANL:", anl, sizeof(anl) / PGLENG, P&anl_vis},
	{"SWP:", wp1,  sizeof(wp1) / PGLENG,  P&anl_vis},
	{"HK1:", hk1, sizeof(hk1) / PGLENG, P&hk_vis[HK1]},
	{"DWP:", dwp, sizeof(dwp) / PGLENG, P&anl_vis},
	{"QSM:", qsm, sizeof(qsm) / PGLENG, P&qsm_vis},
	{"WSP:", ze6, sizeof(ze6) / PGLENG, P&ze_vis[6]},
	{"ESW:", ze7, sizeof(ze7) / PGLENG, P&ze_vis[7]},
	{"DIA;", dia, sizeof(dia) / PGLENG, P&zlt_vis},
	{"MOD;", modbusParli, sizeof(modbusParli) / PGLENG, P&sys_vis},
	{"ALK;", alk, sizeof(alk) / PGLENG, P&syc_vis},
	{"ZLT;", zlt, sizeof(zlt) / PGLENG, P&zlt_vis},
	{"TES;", tes, sizeof(tes) / PGLENG, P&tes_vis},
	{"GPR;", gpr, sizeof(gpr) / PGLENG, P&tes_vis},
	{"SYS;", sys, sizeof(sys) / PGLENG, P&sys_vis}
} 

