// Diese Datei wurde automatisch am : 20.06.2017 um 16:33:14 generiert und entspricht der Systemversion nach 31.05.2017 13:55:19!!!
// Path: d:\RIEcon36C\Projekte\OrtC_sys\CStrasse\CHeiz\FWR0200_CSYS\Komtabparser.exe

#include "defins.h"
#include "struct.h"
#include "projdef.h"
#include "sramext.h"
#include "ustruct.h"
#include "uconstext.h"
#include "uramext.h"
#include "snoinitext.h"
#include "unoinitext.h"
#include "userdef.h"
#include "uconstext.h"
#include "constext.h"
#include "konvform.h"
#include "uskonvform.h"
#include "modbus.h"

#if MODBUS_UNI > 0

//-----------------------------------
// Slave
//-----------------------------------
#if MODBUS_SLAVE == 1

	const modbusSlaveTableRow modbusSlaveTable[] =  {
	//{Adresse des Datenpunkts,	{Riedel Typ,Komma},	SpezialKonvertierung,	Registeradresse,	Registeranzahl, Berechtigung, Timeout[m], Fallback}
		{P&Kategorie_Typ,                              {ASCII_FORM,  15},          NONE,    0,  8, READ_ONLY,  0,   FALSE}, // {"***:"," RIEDEL  R66E   ","       ", P&Kategorie_Typ,				ASCII_FORM, 0, P&vis,		V1, 0, 0},
		{0,                                            {UHR_FORM,   0},            NONE,    8,  1, READ_WRITE, 0,   FALSE}, // {" 01:"," UHRZEIT        ","       ",				0,									UHR_FORM, 0, P&vis,		V1, 0, 0},
		{0,                                            {DATUM_FORM,   0},          NONE,    9,  2, READ_WRITE, 0,   FALSE}, // {" 02:"," DATUM          ","       ",				0,								DATUM_FORM, 0, P&vis,		V1, 0, 0},
		{P&bst,                                        {US_INT,   0},              NONE,   11,  1, READ_ONLY,  0,   FALSE}, // {"*03:"," BETRIEBSSTUNDEN"," h     ", P&bst,											US_INT, 0, P&vis,		V1, 0, 0},
		{P&LeerData[0],                                {US_CHAR,   0},             NONE,   12,  1, READ_WRITE, 0,   FALSE}, // {" ->;"," leerData1      ","       ", P&LeerData[0], 									US_CHAR, 0, P&hid2,	V1, 0, 0},
		{P&LeerData[0],                                {US_CHAR,   0},             NONE,   13,  1, READ_WRITE, 0,   FALSE}, // {" ->;"," leerData2      ","       ", P&LeerData[0], 									US_CHAR, 0, P&hid2,	V1, 0, 0},
		{P&LeerData[0],                                {US_CHAR,   0},             NONE,   14,  1, READ_WRITE, 0,   FALSE}, // {" ->;"," leerData3      ","       ", P&LeerData[0], 									US_CHAR, 0, P&hid2,	V1, 0, 0},
		{P&LeerData[0],                                {US_CHAR,   0},             NONE,   15,  1, READ_WRITE, 0,   FALSE}, // {" ->;"," leerData4      ","       ", P&LeerData[0], 									US_CHAR, 0, P&hid2,	V1, 0, 0},
		{P&LeerSend[0],                                {S_INT,   0},               NONE,   16,  1, READ_WRITE, 0,   FALSE}, // {" ->;"," leerSend1      ","       ", P&LeerSend[0], 									S_INT, 0, P&hid2,	V1, 0, 0},
		{P&LeerSend[0],                                {S_INT,   0},               NONE,   17,  1, READ_WRITE, 0,   FALSE}, // {" ->;"," leerSend2      ","       ", P&LeerSend[0], 									S_INT, 0, P&hid2,	V1, 0, 0},
		{P&LeerSend[0],                                {S_INT,   0},               NONE,   18,  1, READ_WRITE, 0,   FALSE}, // {" ->;"," leerSend3      ","       ", P&LeerSend[0], 									S_INT, 0, P&hid2,	V1, 0, 0},
		{P&LeerSend[0],                                {S_INT,   0},               NONE,   19,  1, READ_WRITE, 0,   FALSE}, // {" ->;"," leerSend4      ","       ", P&LeerSend[0], 									S_INT, 0, P&hid2,	V1, 0, 0},
		{P&ta1m,                                       {ANA_FORM,   1},            NONE,   20,  1, READ_WRITE, 0,   FALSE}, // {" 12:"," AUSSENLUFTTEMP."," C    ", P&ta1m,										ANA_FORM, 1, P&vis,		V1, 0, 0},
		{P&ta1m,                                       {ANA_FORM, 129},            NONE,   21,  1, READ_WRITE, 0,   FALSE}, // {" 12:"," AUSSENLUFTTEMP."," C    ", P&ta1m,							 	 ANA_FORM, 0x81, P&kom,		E1, FUEHLER, 0},
		{P&Ta1mzk,                                     {US_CHAR,   0},             NONE,   22,  1, READ_WRITE, 0,   FALSE}, // {" 13:"," DAEMPFUNGSZEIT "," min   ", P&Ta1mzk,									 US_CHAR, 0, P&vis,		V1, 0, 0},
		{P&ta1mh,                                      {ANA_FORM,   1},            NONE,   23,  1, READ_ONLY,  0,   FALSE}, // {"*14:"," AUSSENT. MITTEL"," C    ", P&ta1mh,									ANA_FORM, 1, P&vis,		V1, 0, 0},
		{P&ta1mh,                                      {ANA_FORM, 129},            NONE,   24,  1, READ_ONLY,  0,   FALSE}, // {"*14:"," AUSSENT. MITTEL"," C    ", P&ta1mh,							 ANA_FORM, 0x81, P&kom,		V1, 0, 0},
		{P&Ta1mhzk,                                    {US_CHAR,   0},             NONE,   25,  1, READ_WRITE, 0,   FALSE}, // {" 15:"," MITTLUNGS-ZEIT "," h     ", P&Ta1mhzk,								 US_CHAR, 0, P&vis,		V1, 0, 0},
		{P&ta1mh_temp,                                 {S_INT,   1},               NONE,   26,  1, READ_WRITE, 0,   FALSE}, // {" 15;"," MITTLUNGS-INIT "," C    ", P&ta1mh_temp,								 S_INT, 1, P&hid1,	V1, 0, 0},
		{P&Tae,                                        {US_INT,   1},              NONE,   27,  1, READ_WRITE, 0,   FALSE}, // {" 16:"," Ta-WINTER [EIN]"," C    ", P&Tae,											US_INT, 1, P&vis,		V1, 0, 0},
		{P&Taa,                                        {US_INT,   1},              NONE,   28,  1, READ_WRITE, 0,   FALSE}, // {" 17:"," Ta-SOMMER [AUS]"," C    ", P&Taa,											US_INT, 1, P&vis,		V1, 0, 0},
		{P&sowi,                                       {JANEIN_FORM,   0},         NONE,   29,  1, READ_ONLY,  0,   FALSE}, // {"*18:"," SOMMER ?       ","       ", P&sowi,			 					 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
		{P&HardHand,                                   {JANEIN_FORM,   0},         NONE,   30,  1, READ_ONLY,  0,   FALSE}, // {"*80:"," SCHALTER HAND ?","       ", P&HardHand,							 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
		{P&sw_stat_info,                               {ASCII_FORM,   6},          NONE,   31,  3, READ_ONLY,  0,   FALSE}, // {"*81:"," R66 SCHALTER1-6","       ", P&sw_stat_info,						DYN_ASCII_FORM, 6, P&vis,		V1, 0, 0},
		{P&mod37[0].sw_stat_info,                      {ASCII_FORM,   3},          NONE,   34,  2, READ_ONLY,  0,   FALSE}, // {"*82:"," R37_1 SCHALT1-3","       ", P&mod37[0].sw_stat_info,	DYN_ASCII_FORM, 3, P&vis,		V1, 0, 0},
		{P&sstm[STANDARD],                             {US_CHAR,   0},             NONE,   36,  1, READ_ONLY,  0,   FALSE}, // {"*90:"," SMGRUP STANDARD","       ", P&sstm[STANDARD],			 	US_CHAR, 0, P&vis,		A1, GRUP|STANDARD, 0},
		{P&sstm[FUEHLER],                              {US_CHAR,   0},             NONE,   37,  1, READ_ONLY,  0,   FALSE}, // {"*91:"," SMGRUP FUEHLER ","       ", P&sstm[FUEHLER],			 	US_CHAR, 0, P&vis,		A1, GRUP|FUEHLER,  0},
		{P&sstm[MODULE],                               {US_CHAR,   0},             NONE,   38,  1, READ_ONLY,  0,   FALSE}, // {"*92:"," SMGRUP MODULE  ","       ", P&sstm[MODULE],			 		US_CHAR, 0, P&vis,		A1, GRUP|MODULE,   0},
		{P&sstm_alarme,                                {JANEIN_FORM,   0},         NONE,   39,  1, READ_ONLY,  0,   FALSE}, // {"*->:"," SSTM ALARME    ","       ", P&sstm_alarme,		 	JANEIN_FORM, 0, P&vis,		V1, 0, 0},
		{P&sstm_all,                                   {JANEIN_FORM,   0},         NONE,   40,  1, READ_ONLY,  0,   FALSE}, // {"*->:"," SSTM AL+FUEHLER","       ", P&sstm_all,		 			JANEIN_FORM, 0, P&vis,		V1, 0, 0},
		{P&ssmBusPu,                                   {JANEIN_FORM,   0},         NONE,   41,  1, READ_ONLY,  0,   FALSE}, // {"*94:"," SSTM PUMPENBUS?","       ", P&ssmBusPu,			  		JANEIN_FORM, 0, P&vis,		A1, EINZEL, 0},
		{P&quit_taste,                                 {US_CHAR,   0},             NONE,   42,  1, READ_WRITE, 0,   FALSE}, // {" 96:"," QUITTIER-TASTE "," EIN=1 ", P&quit_taste,			 				US_CHAR,  0, P&hid1,	V1, 0, 0},
		{P&Ntmod,                                      {ASCII_FORM,  15},          NONE,   43,  8, READ_ONLY,  0,   FALSE}, // {"***:"," NETZTRENNUNG   ","       ", P&Ntmod,							ASCII_FORM, 0, P&vis,		V1},
		{P&TRP[NT1],                                   {ANA_FORMP,   1},           NONE,   51,  1, READ_ONLY,  0,   FALSE}, // {"*02:"," RUECKLAUF PRIM."," C    ", P&TRP[NT1],						 ANA_FORMP, 1, P&vis,		V1, 0, 0},
		{P&TRP[NT1],                                   {ANA_FORMP, 129},           NONE,   52,  1, READ_ONLY,  0,   FALSE}, // {"*02:"," RUECKLAUF PRIM."," C    ", P&TRP[NT1],					ANA_FORMP, 0x81, P&kom,		E1, FUEHLER, 0},
		{P&TVSEK[NT1],                                 {ANA_FORMP,   1},           NONE,   53,  1, READ_ONLY,  0,   FALSE}, // {"*03:"," VORLAUF SEKUND."," C    ", P&TVSEK[NT1],					 ANA_FORMP, 1, P&vis,		V1, 0, 0},
		{P&TVSEK[NT1],                                 {ANA_FORMP, 129},           NONE,   54,  1, READ_ONLY,  0,   FALSE}, // {"*03:"," VORLAUF SEKUND."," C    ", P&TVSEK[NT1],				ANA_FORMP, 0x81, P&kom,		E1, FUEHLER, 0},
		{P&nts[NT1].Tvpa,                              {US_INT,   1},              NONE,   55,  1, READ_WRITE, 0,   FALSE}, // {" 11:"," ANHEBUNG       "," K     ", P&nts[NT1].Tvpa,					US_INT, 1, P&vis,		V1, 0, 0},
		{P&nts[NT1].Tvma,                              {US_INT,   1},              NONE,   56,  1, READ_WRITE, 0,   FALSE}, // {" 12:"," VORLAUF   MAX  "," C    ", P&nts[NT1].Tvma,					US_INT, 1, P&vis,		V1, 0, 0},
		{P&nts[NT1].Tvmi,                              {US_INT,   1},              NONE,   57,  1, READ_WRITE, 0,   FALSE}, // {" 13:"," VORLAUF   MIN  "," C    ", P&nts[NT1].Tvmi,					US_INT, 1, P&vis,		V1, 0, 0},
		{P&nts[NT1].Trma,                              {US_INT,   1},              NONE,   58,  1, READ_WRITE, 0,   FALSE}, // {" 18:"," RUECKLAUF MAX  "," C    ", P&nts[NT1].Trma,					US_INT, 1, P&vis,		V1, 0, 0},
		{P&nts[NT1].Kpr,                               {US_INT,   2},              NONE,   59,  1, READ_WRITE, 0,   FALSE}, // {" 19:"," Xp-RUECKL.BEGR.","       ", P&nts[NT1].Kpr,						US_INT, 2, P&vis,		V1, 0, 0},
		{P&ntd[NT1].tvsb,                              {US_INT,   1},              NONE,   60,  1, READ_ONLY,  0,   FALSE}, // {"*20:"," VORLAUF BERECHN"," C    ", P&ntd[NT1].tvsb,					US_INT, 1, P&vis,		V1, 0, 0},
		{P&nts[NT1].TabwMax,                           {US_CHAR,   1},             NONE,   61,  1, READ_WRITE, 0,   FALSE}, // {" 68;"," TDIFF.ALARM EIN"," K     ", P&nts[NT1].TabwMax,			 US_CHAR, 1, P&hid1,	V1, 0, 0},
		{P&nts[NT1].TabwZeit,                          {US_CHAR,   0},             NONE,   62,  1, READ_WRITE, 0,   FALSE}, // {" 69;"," ZVERZ.ALARM EIN"," min   ", P&nts[NT1].TabwZeit,		 US_CHAR, 0, P&hid1,	V1, 0, 0},
		{P&ntd[NT1].rlbegr,                            {JANEIN_FORM,   0},         NONE,   63,  1, READ_ONLY,  0,   FALSE}, // {"*85:"," RUECKL.BEGR. ? ","       ", P&ntd[NT1].rlbegr,	 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
		{P&ntd[NT1].abwAlarm,                          {JANEIN_FORM,   0},         NONE,   64,  1, READ_ONLY,  0,   FALSE}, // {"*86:"," SM REGELABW.?  ","       ", P&ntd[NT1].abwAlarm, JANEIN_FORM, 0, P&vis, 	A1, EINZEL, 0},
		{P&STWNT[NT1],                                 {JANEIN_FORMIP,   0},       NONE,   65,  1, READ_ONLY,  0,   FALSE}, // {"*87:"," SM STW ?       ","       ", P&STWNT[NT1], 		 JANEIN_FORMIP, 0, P&vis,		A1, EINZEL, 0},
		{P&nts[NT1].Haut,                              {JANEIN_FORM,   0},         NONE,   66,  1, READ_ONLY,  0,   FALSE}, // {"*89:"," HANDBETRIEB ?  ","       ", P&nts[NT1].Haut,		 JANEIN_FORM, 0, P&vis,		E1, EREIGNIS, 0},
		{P&nts[NT1].Kp,                                {US_INT,   2},              NONE,   67,  1, READ_WRITE, 0,   FALSE}, // {" 90;"," P-VERSTAERKUNG "," %/K   ", P&nts[NT1].Kp,						US_INT, 2, P&hid1,	V1, 0, 0},
		{P&nts[NT1].Kd,                                {US_INT,   2},              NONE,   68,  1, READ_WRITE, 0,   FALSE}, // {" 91;"," D-VERSTAERKUNG ","       ", P&nts[NT1].Kd,						US_INT, 2, P&hid1,	V1, 0, 0},
		{P&nts[NT1].Ts,                                {US_INT,   1},              NONE,   69,  1, READ_WRITE, 0,   FALSE}, // {" 92;"," TASTZEIT       "," s     ", P&nts[NT1].Ts,						US_INT, 1, P&hid1,	V1, 0, 0},
		{P&nts[NT1].Tn,                                {US_INT,   1},              NONE,   70,  1, READ_WRITE, 0,   FALSE}, // {" 93;"," NACHSTELLZEIT  "," s     ", P&nts[NT1].Tn,						US_INT, 1, P&hid1,	V1, 0, 0},
		{P&ntd[NT1].tsol,                              {US_INT,   1},              NONE,   71,  1, READ_ONLY,  0,   FALSE}, // {"*96;"," SOLLWERT       "," C    ", P&ntd[NT1].tsol,					US_INT, 1, P&hid1,	V1, 0, 0},
		{P&ntd[NT1].ei,                                {S_INT,   1},               NONE,   72,  1, READ_ONLY,  0,   FALSE}, // {"*97;"," REGELABWEICHUNG"," K     ", P&ntd[NT1].ei,						 S_INT, 1, P&hid1,	V1, 0, 0},
		{P&RVENTNT[NT1],                               {AOUT_FORMP,   1},          NONE,   73,  1, READ_ONLY,  0,   FALSE}, // {"*98;"," VENTILSTELLUNG "," %     ", P&RVENTNT[NT1],				AOUT_FORMP, 1, P&hid1,	V1, 0, 0},
		{P&nts[NT1].Haut,                              {US_CHAR,   0},             NONE,   74,  1, READ_WRITE, 0,   FALSE}, // {" 99;"," HAND/AUTOMATIK "," HAND=1", P&nts[NT1].Haut,				 US_CHAR, 0, P&hid1,	V1, 0, 0},
		{P&nts[NT1].Vstell,                            {US_INT,   1},              NONE,   75,  1, READ_WRITE, 0,   FALSE}, // {" ->:"," VENTIL STELLEN "," %     ", P&nts[NT1].Vstell,			  US_INT, 1, P&hid1,	V1, 0, 0},
		{P&hkd[HK1].raumname,                          {ASCII_FORM,  15},          NONE,   76,  8, READ_WRITE, 0,   FALSE}, // {"_**:"," HEIZKREIS 1    ","       ", P&hkd[HK1].raumname,	ASCII_FORM, 0, P&vis,		V1, 0, 0},
		{P&TVS[HK1],                                   {ANA_FORMP,   1},           NONE,   84,  1, READ_ONLY,  0,   FALSE}, // {"*01:"," VORLAUF   IST  "," C    ", P&TVS[HK1],						 ANA_FORMP, 1, P&vis,		V1, 0, 0},
		{P&TVS[HK1],                                   {ANA_FORMP, 129},           NONE,   85,  1, READ_ONLY,  0,   FALSE}, // {"*01:"," VORLAUF   IST  "," C    ", P&TVS[HK1],					ANA_FORMP, 0x81, P&kom,		E1, FUEHLER, 0},
		{P&TRS[HK1],                                   {ANA_FORMP,   1},           NONE,   86,  1, READ_ONLY,  0,   FALSE}, // {"*02:"," RUECKLAUF IST  "," C    ", P&TRS[HK1],						 ANA_FORMP, 1, P&vis,		V1, 0, 0},
		{P&TRS[HK1],                                   {ANA_FORMP, 129},           NONE,   87,  1, READ_ONLY,  0,   FALSE}, // {"*02:"," RUECKLAUF IST  "," C    ", P&TRS[HK1],					ANA_FORMP, 0x81, P&kom,		E1, FUEHLER, 0},
		{P&hks[HK1].SoWiExtra,                         {US_CHAR,   0},             NONE,   88,  1, READ_WRITE, 0,   FALSE}, // {" 06;"," SO/WI HK-EXTRA "," 1=JA  ", P&hks[HK1].SoWiExtra,		 US_CHAR, 0, P&hid1,	V1, 0, 0},
		{P&hks[HK1].Tae,                               {US_INT,   1},              NONE,   89,  1, READ_WRITE, 0,   FALSE}, // {" 07;"," Ta-WINTER [EIN]"," C    ", P&hks[HK1].Tae,						US_INT, 1, P&hid1,	V1, 0, 0},
		{P&hks[HK1].Taa,                               {US_INT,   1},              NONE,   90,  1, READ_WRITE, 0,   FALSE}, // {" 08;"," Ta-SOMMER [AUS]"," C    ", P&hks[HK1].Taa,						US_INT, 1, P&hid1,	V1, 0, 0},
		{P&hkd[HK1].sowi,                              {JANEIN_FORM,   0},         NONE,   91,  1, READ_ONLY,  0,   FALSE}, // {"*09;"," SOMMER ?       ","       ", P&hkd[HK1].sowi,		 JANEIN_FORM, 0, P&hid1,	V1, 0, 0},
		{P&hks[HK1].Anst,                              {US_INT,   2},              NONE,   92,  1, READ_WRITE, 0,   FALSE}, // {" 10:"," STEIGUNG       ","       ", P&hks[HK1].Anst,					US_INT, 2, P&vis,		V1, 0, 0},
		{P&hks[HK1].Tvpa,                              {US_INT,   1},              NONE,   93,  1, READ_WRITE, 0,   FALSE}, // {" 11:"," NIVEAU         "," C    ", P&hks[HK1].Tvpa,					US_INT, 1, P&vis,		V1, 0, 0},
		{P&hks[HK1].Tvma,                              {US_INT,   1},              NONE,   94,  1, READ_WRITE, 0,   FALSE}, // {" 12:"," VORLAUF   MAX  "," C    ", P&hks[HK1].Tvma,					US_INT, 1, P&vis,		V1, 0, 0},
		{P&hks[HK1].Tvmi,                              {US_INT,   1},              NONE,   95,  1, READ_WRITE, 0,   FALSE}, // {" 13:"," VORLAUF   MIN  "," C    ", P&hks[HK1].Tvmi,					US_INT, 1, P&vis,		V1, 0, 0},
		{P&hks[HK1].Trma,                              {US_INT,   1},              NONE,   96,  1, READ_WRITE, 0,   FALSE}, // {" 18:"," RUECKLAUF MAX  "," C    ", P&hks[HK1].Trma,					US_INT, 1, P&vis,		V1, 0, 0},
		{P&hks[HK1].Kpr,                               {US_INT,   2},              NONE,   97,  1, READ_WRITE, 0,   FALSE}, // {" 19:"," Xp-RUECKL.BEGR.","       ", P&hks[HK1].Kpr,						US_INT, 2, P&vis,		V1, 0, 0},
		{P&hkd[HK1].tvsb,                              {US_INT,   1},              NONE,   98,  1, READ_ONLY,  0,   FALSE}, // {"*20:"," VORLAUF BERECHN"," C    ", P&hkd[HK1].tvsb,					US_INT, 1, P&vis,		V1, 0, 0},
		{P&hks[HK1].TvpAnh,                            {US_INT,   1},              NONE,   99,  1, READ_WRITE, 0,   FALSE}, // {" 28:"," ANFORD.ANHEBUNG"," K     ", P&hks[HK1].TvpAnh,				US_INT, 1, P&vis,			V1, 0, 0},
		{P&abs_tab[HK1][0].begin,                      {ZEIT_FORM,   0},           NONE,  100,  1, READ_WRITE, 0,   FALSE}, // {" 30:"," ABSENK-BEGIN WO"," h:min ", P&abs_tab[HK1][0].begin,ZEIT_FORM,0, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][0].dauer,                      {US_CHAR,   0},             NONE,  101,  1, READ_WRITE, 0,   FALSE}, // {" 31:"," ABSENK-DAUER WO"," h     ", P&abs_tab[HK1][0].dauer, US_CHAR, 0, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][0].abwert,                     {US_INT,   1},              NONE,  102,  1, READ_WRITE, 0,   FALSE}, // {" 32:"," ABSENK-WERT  WO"," K     ", P&abs_tab[HK1][0].abwert,	US_INT, 1, P&vis,		V1, 0, 0},
		{P&setwoche[HK1],                              {US_CHAR,   0},             NONE,  103,  1, READ_WRITE, 0,   FALSE}, // {" 34:"," GANZE WOCHE SET"," 1=JA  ", P&setwoche[HK1],				 US_CHAR, 0, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][1].begin,                      {ZEIT_FORM,   0},           NONE,  104,  1, READ_WRITE, 0,   FALSE}, // {" 35:"," ABSENK-BEGIN Mo"," h:min ", P&abs_tab[HK1][1].begin,ZEIT_FORM,0, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][1].dauer,                      {US_CHAR,   0},             NONE,  105,  1, READ_WRITE, 0,   FALSE}, // {" ->:"," ABSENK-DAUER Mo"," h     ", P&abs_tab[HK1][1].dauer, US_CHAR, 0, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][1].abwert,                     {US_INT,   1},              NONE,  106,  1, READ_WRITE, 0,   FALSE}, // {" ->:"," ABSENK-WERT  Mo"," K     ", P&abs_tab[HK1][1].abwert,	US_INT, 1, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][2].begin,                      {ZEIT_FORM,   0},           NONE,  107,  1, READ_WRITE, 0,   FALSE}, // {" 36:"," ABSENK-BEGIN Di"," h:min ", P&abs_tab[HK1][2].begin,ZEIT_FORM,0, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][2].dauer,                      {US_CHAR,   0},             NONE,  108,  1, READ_WRITE, 0,   FALSE}, // {" ->:"," ABSENK-DAUER Di"," h     ", P&abs_tab[HK1][2].dauer, US_CHAR, 0, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][2].abwert,                     {US_INT,   1},              NONE,  109,  1, READ_WRITE, 0,   FALSE}, // {" ->:"," ABSENK-WERT  Di"," K     ", P&abs_tab[HK1][2].abwert,	US_INT, 1, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][3].begin,                      {ZEIT_FORM,   0},           NONE,  110,  1, READ_WRITE, 0,   FALSE}, // {" 37:"," ABSENK-BEGIN Mi"," h:min ", P&abs_tab[HK1][3].begin,ZEIT_FORM,0, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][3].dauer,                      {US_CHAR,   0},             NONE,  111,  1, READ_WRITE, 0,   FALSE}, // {" ->:"," ABSENK-DAUER Mi"," h     ", P&abs_tab[HK1][3].dauer, US_CHAR, 0, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][3].abwert,                     {US_INT,   1},              NONE,  112,  1, READ_WRITE, 0,   FALSE}, // {" ->:"," ABSENK-WERT  Mi"," K     ", P&abs_tab[HK1][3].abwert,	US_INT, 1, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][4].begin,                      {ZEIT_FORM,   0},           NONE,  113,  1, READ_WRITE, 0,   FALSE}, // {" 38:"," ABSENK-BEGIN Do"," h:min ", P&abs_tab[HK1][4].begin,ZEIT_FORM,0, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][4].dauer,                      {US_CHAR,   0},             NONE,  114,  1, READ_WRITE, 0,   FALSE}, // {" ->:"," ABSENK-DAUER Do"," h     ", P&abs_tab[HK1][4].dauer, US_CHAR, 0, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][4].abwert,                     {US_INT,   1},              NONE,  115,  1, READ_WRITE, 0,   FALSE}, // {" ->:"," ABSENK-WERT  Do"," K     ", P&abs_tab[HK1][4].abwert,	US_INT, 1, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][5].begin,                      {ZEIT_FORM,   0},           NONE,  116,  1, READ_WRITE, 0,   FALSE}, // {" 39:"," ABSENK-BEGIN Fr"," h:min ", P&abs_tab[HK1][5].begin,ZEIT_FORM,0, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][5].dauer,                      {US_CHAR,   0},             NONE,  117,  1, READ_WRITE, 0,   FALSE}, // {" ->:"," ABSENK-DAUER Fr"," h     ", P&abs_tab[HK1][5].dauer, US_CHAR, 0, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][5].abwert,                     {US_INT,   1},              NONE,  118,  1, READ_WRITE, 0,   FALSE}, // {" ->:"," ABSENK-WERT  Fr"," K     ", P&abs_tab[HK1][5].abwert,	US_INT, 1, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][6].begin,                      {ZEIT_FORM,   0},           NONE,  119,  1, READ_WRITE, 0,   FALSE}, // {" 40:"," ABSENK-BEGIN Sa"," h:min ", P&abs_tab[HK1][6].begin,ZEIT_FORM,0, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][6].dauer,                      {US_CHAR,   0},             NONE,  120,  1, READ_WRITE, 0,   FALSE}, // {" ->:"," ABSENK-DAUER Sa"," h     ", P&abs_tab[HK1][6].dauer, US_CHAR, 0, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][6].abwert,                     {US_INT,   1},              NONE,  121,  1, READ_WRITE, 0,   FALSE}, // {" ->:"," ABSENK-WERT  Sa"," K     ", P&abs_tab[HK1][6].abwert,	US_INT, 1, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][7].begin,                      {ZEIT_FORM,   0},           NONE,  122,  1, READ_WRITE, 0,   FALSE}, // {" 41:"," ABSENK-BEGIN So"," h:min ", P&abs_tab[HK1][7].begin,ZEIT_FORM,0, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][7].dauer,                      {US_CHAR,   0},             NONE,  123,  1, READ_WRITE, 0,   FALSE}, // {" ->:"," ABSENK-DAUER So"," h     ", P&abs_tab[HK1][7].dauer, US_CHAR, 0, P&vis,		V1, 0, 0},
		{P&abs_tab[HK1][7].abwert,                     {US_INT,   1},              NONE,  124,  1, READ_WRITE, 0,   FALSE}, // {" ->:"," ABSENK-WERT  So"," K     ", P&abs_tab[HK1][7].abwert,	US_INT, 1, P&vis,		V1, 0, 0},
		{P&abs_ram[HK1].absen,                         {JANEIN_FORM,   0},         NONE,  125,  1, READ_ONLY,  0,   FALSE}, // {"*->;"," ZEITABSENKPHASE","       ", P&abs_ram[HK1].absen,	 JANEIN_FORM, 0, P&hid1,V1, 0, 0},
		{P&hks[HK1].TaHeizgrenze,                      {S_INT,   1},               NONE,  126,  1, READ_WRITE, 0,   FALSE}, // {" 50:"," HEIZ-TaGRENZE  "," C    ", P&hks[HK1].TaHeizgrenze,		 S_INT, 1, P&vis,	V1, 0, 0},
		{P&hks[HK1].TaFrostgrenze,                     {S_INT,   1},               NONE,  127,  1, READ_WRITE, 0,   FALSE}, // {" 51:"," FROST-TaGRENZE "," C    ", P&hks[HK1].TaFrostgrenze,		 S_INT, 1, P&vis,	V1, 0, 0},
		{P&hks[HK1].AbschZeitKonst,                    {US_INT,   1},              NONE,  128,  1, READ_WRITE, 0,   FALSE}, // {" 52:"," ABSCH-ZEITKONST"," h/K   ", P&hks[HK1].AbschZeitKonst,	US_INT, 1, P&vis,	V1, 0, 0},
		{P&hks[HK1].Sauf,                              {US_CHAR,   0},             NONE,  129,  1, READ_WRITE, 0,   FALSE}, // {" 60:"," SCHNELLAUFHEIZ."," JA=1  ", P&hks[HK1].Sauf,				 US_CHAR, 0, P&vis,		V1, 0, 0},
		{P&hks[HK1].Swhk,                              {US_CHAR,   0},             NONE,  130,  1, READ_WRITE, 0,   FALSE}, // {" 61:"," SO/WI-AUTOMATIK"," JA=1  ", P&hks[HK1].Swhk,				 US_CHAR, 0, P&vis,		V1, 0, 0},
		{P&hks[HK1].TabwMax,                           {US_CHAR,   1},             NONE,  131,  1, READ_WRITE, 0,   FALSE}, // {" 68;"," TDIFF.ALARM EIN"," K     ", P&hks[HK1].TabwMax,			 US_CHAR, 1, P&hid1,	V1, 0, 0},
		{P&hks[HK1].TabwZeit,                          {US_CHAR,   0},             NONE,  132,  1, READ_WRITE, 0,   FALSE}, // {" 69;"," ZVERZ.ALARM EIN"," min   ", P&hks[HK1].TabwZeit,		 US_CHAR, 0, P&hid1,	V1, 0, 0},
		{P&PU[HK1],                                    {JANEIN_FORMOP,   0},       NONE,  133,  1, READ_ONLY,  0,   FALSE}, // {"*72:"," HEIZ-PUMPE EIN?","       ", P&PU[HK1], 				 JANEIN_FORMOP, 0, P&vis,		V1, 0, 0},
		{P&hkd[HK1].regie_txt,                         {ASCII_FORM,  15},          NONE,  134,  8, READ_ONLY,  0,   FALSE}, // {"*80:"," BETRIEBS-REGIE ","       ", P&hkd[HK1].regie_txt, DYN_ASCII_FORM, 0, P&vis,		V1, 0, 0},
		{P&hkd[HK1].absen,                             {JANEIN_FORM,   0},         NONE,  142,  1, READ_ONLY,  0,   FALSE}, // {"*81:"," ABSENKPHASE ?  ","       ", P&hkd[HK1].absen,		 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
		{P&hkd[HK1].absch,                             {JANEIN_FORM,   0},         NONE,  143,  1, READ_ONLY,  0,   FALSE}, // {"*->:"," ABSCHALTPHASE ?","       ", P&hkd[HK1].absch,		 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
		{P&hkd[HK1].frost,                             {JANEIN_FORM,   0},         NONE,  144,  1, READ_ONLY,  0,   FALSE}, // {"*->:"," FROSTBETRIEB ? ","       ", P&hkd[HK1].frost,		 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
		{P&hkd[HK1].aufhe,                             {JANEIN_FORM,   0},         NONE,  145,  1, READ_ONLY,  0,   FALSE}, // {"*82:"," AUFHEIZPHASE ? ","       ", P&hkd[HK1].aufhe,		 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
		{P&hkd[HK1].somme,                             {JANEIN_FORM,   0},         NONE,  146,  1, READ_ONLY,  0,   FALSE}, // {"*83:"," SOMMERBETRIEB ?","       ", P&hkd[HK1].somme,	 	 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
		{P&hkd[HK1].vorra,                             {JANEIN_FORM,   0},         NONE,  147,  1, READ_ONLY,  0,   FALSE}, // {"*84:"," WW-VORRANG ?   ","       ", P&hkd[HK1].vorra,	 	 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
		{P&hkd[HK1].rlbegr,                            {JANEIN_FORM,   0},         NONE,  148,  1, READ_ONLY,  0,   FALSE}, // {"*85:"," RUECKL.BEGR. ? ","       ", P&hkd[HK1].rlbegr,	 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
		{P&hkd[HK1].abwAlarm,                          {JANEIN_FORM,   0},         NONE,  149,  1, READ_ONLY,  0,   FALSE}, // {"*86:"," SM REGELABW.?  ","       ", P&hkd[HK1].abwAlarm, JANEIN_FORM, 0, P&vis, 	A1, EINZEL,   0},
		{P&PUAL[HK1],                                  {JANEIN_FORMIP,   0},       NONE,  150,  1, READ_ONLY,  0,   FALSE}, // {"*88:"," SM HEIZ-PUMPE ?","       ", P&PUAL[HK1], 			 JANEIN_FORMIP, 0, P&vis,		A1, EINZEL,   0},
		{P&hks[HK1].Haut,                              {JANEIN_FORM,   0},         NONE,  151,  1, READ_ONLY,  0,   FALSE}, // {"*89:"," HANDBETRIEB ?  ","       ", P&hks[HK1].Haut,		 JANEIN_FORM, 0, P&vis,		E1, EREIGNIS, 0},
		{P&hks[HK1].Kp,                                {US_INT,   2},              NONE,  152,  1, READ_WRITE, 0,   FALSE}, // {" 90;"," P-VERSTAERKUNG "," %/K   ", P&hks[HK1].Kp,						US_INT, 2, P&hid1,	V1, 0, 0},
		{P&hks[HK1].Kd,                                {US_INT,   2},              NONE,  153,  1, READ_WRITE, 0,   FALSE}, // {" 91;"," D-VERSTAERKUNG ","       ", P&hks[HK1].Kd,						US_INT, 2, P&hid1,	V1, 0, 0},
		{P&hks[HK1].Ts,                                {US_INT,   1},              NONE,  154,  1, READ_WRITE, 0,   FALSE}, // {" 92;"," TASTZEIT       "," s     ", P&hks[HK1].Ts,						US_INT, 1, P&hid1,	V1, 0, 0},
		{P&hks[HK1].Tn,                                {US_INT,   1},              NONE,  155,  1, READ_WRITE, 0,   FALSE}, // {" 93;"," NACHSTELLZEIT  "," s     ", P&hks[HK1].Tn,						US_INT, 1, P&hid1,	V1, 0, 0},
		{P&hks[HK1].Y_rel_min,                         {US_INT,   1},              NONE,  156,  1, READ_WRITE, 0,   FALSE}, // {" 94;"," VENTILSTELL.MIN"," %     ", P&hks[HK1].Y_rel_min,	 		US_INT, 1, P&hid1,	V1, 0, 0},
		{P&hks[HK1].Y_rel_beg,                         {US_INT,   1},              NONE,  157,  1, READ_WRITE, 0,   FALSE}, // {" 95;"," OEFFNUNGSBEGINN"," %     ", P&hks[HK1].Y_rel_beg,	 		US_INT, 1, P&hid1,	V1, 0, 0},
		{P&hkd[HK1].tsol,                              {US_INT,   1},              NONE,  158,  1, READ_ONLY,  0,   FALSE}, // {"*96;"," SOLLWERT       "," C    ", P&hkd[HK1].tsol,					US_INT, 1, P&hid1,	V1, 0, 0},
		{P&hkd[HK1].ei,                                {S_INT,   1},               NONE,  159,  1, READ_ONLY,  0,   FALSE}, // {"*97;"," REGELABWEICHUNG"," K     ", P&hkd[HK1].ei,						 S_INT, 1, P&hid1,	V1, 0, 0},
		{P&RVENT[HK1],                                 {AOUT_FORMP,   1},          NONE,  160,  1, READ_ONLY,  0,   FALSE}, // {"*98;"," VENTILSTELLUNG "," %     ", P&RVENT[HK1],					AOUT_FORMP, 1, P&hid1,	V1, 0, 0},
		{P&hks[HK1].Haut,                              {US_CHAR,   0},             NONE,  161,  1, READ_WRITE, 0,   FALSE}, // {" 99;"," HAND/AUTOMATIK "," HAND=1", P&hks[HK1].Haut,				 US_CHAR, 0, P&hid1,	V1, 0, 0},
		{P&hks[HK1].Puea,                              {US_CHAR,   0},             NONE,  162,  1, READ_WRITE, 0,   FALSE}, // {" ->:"," PUMPE EIN/AUS  "," EIN=1 ", P&hks[HK1].Puea,		 		 US_CHAR, 0, P&hid1,	V1, 0, 0},
		{P&hks[HK1].Vstell,                            {US_INT,   1},              NONE,  163,  1, READ_WRITE, 0,   FALSE}, // {" ->:"," VENTIL STELLEN "," %     ", P&hks[HK1].Vstell,			  US_INT, 1, P&hid1,	V1, 0, 0},
		{P&Wwmod[0],                                   {ASCII_FORM,  15},          NONE,  164,  8, READ_ONLY,  0,   FALSE}, // {"***:"," WARMWASSER 1   ","       ", P&Wwmod[0],						ASCII_FORM, 0, P&vis,		V1, 0, 0},
		{P&wws[WW1].TvpAnh,                            {US_INT,   1},              NONE,  172,  1, READ_WRITE, 0,   FALSE}, // {" 28:"," ANFORD.ANHEBUNG"," K     ", P&wws[WW1].TvpAnh,				US_INT, 1, P&vis,		V1, 0, 0},
		{P&wws[WW1].Legjn,                             {US_CHAR,   0},             NONE,  173,  1, READ_WRITE, 0,   FALSE}, // {" 30:"," LEGIONELLENTOD "," JA=1  ", P&wws[WW1].Legjn,				 US_CHAR, 0, P&vis,		V1, 0, 0},
		{P&wws[WW1].Legtag,                            {GWOTAG2_FORM,   0},        NONE,  174,  1, READ_WRITE, 0,   FALSE}, // {" 31;"," LEGION.-TAGE   "," Mo=1..", P&wws[WW1].Legtag,	GWOTAG2_FORM, 0, P&hid1,	V1, 0, 0},
		{P&wws[WW1].Legzeit,                           {ZEIT_FORM,   0},           NONE,  175,  1, READ_WRITE, 0,   FALSE}, // {" 32;"," LEGION.-ZEIT   "," h:min ", P&wws[WW1].Legzeit,		 ZEIT_FORM, 0, P&hid1,	V1, 0, 0},
		{P&wws[WW1].Legdau,                            {US_CHAR,   0},             NONE,  176,  1, READ_WRITE, 0,   FALSE}, // {" 33;"," LEGION.-DAUER  "," h     ", P&wws[WW1].Legdau,			 US_CHAR, 0, P&hid1,	V1, 0, 0},
		{P&wws[WW1].TwwzLegio,                         {US_INT,   1},              NONE,  177,  1, READ_WRITE, 0,   FALSE}, // {" 34:"," ZIRK-TEMP.LEGIO"," C    ", P&wws[WW1].TwwzLegio,			US_INT, 1, P&vis,		V1, 0, 0},
		{P&wws[WW1].Puwlna,                            {US_CHAR,   0},             NONE,  178,  1, READ_WRITE, 0,   FALSE}, // {" 40:"," LP-NACHLAUFZEIT"," min   ", P&wws[WW1].Puwlna,			 US_CHAR, 0, P&hid1,	V1, 0, 0},
		{P&hks[HK1].Wwvh[WW1],                         {US_CHAR,   0},             NONE,  179,  1, READ_WRITE, 0,   FALSE}, // {" 60:"," VORRANG VOR HK1"," JA=1  ", P&hks[HK1].Wwvh[WW1],		 US_CHAR, 0, P&vis,		V1, 0, 0},
		{P&hks[HK1].Kpww[WW1],                         {US_INT,   2},              NONE,  180,  1, READ_WRITE, 0,   FALSE}, // {" 61;"," Xp-VORRANG  HK1","       ", P&hks[HK1].Kpww[WW1],		 	US_INT, 2, P&hid1,	V1, 0, 0},
		{P&wws[WW1].Vorrad,                            {US_CHAR,   0},             NONE,  181,  1, READ_WRITE, 0,   FALSE}, // {" 64;"," VORRANGZEIT MAX"," min   ", P&wws[WW1].Vorrad,		 	 US_CHAR, 0, P&hid1,	V1, 0, 0},
		{P&wwd[WW1].puwlsta,                           {US_INT,   0},              NONE,  182,  1, READ_ONLY,  0,   FALSE}, // {"*70;"," LADEPU-STARTS  ","       ", P&wwd[WW1].puwlsta, 			US_INT, 0, P&hid1,	V1, 0, 0},
		{P&wwd[WW1].puwlh,                             {US_INT,   0},              NONE,  183,  1, READ_ONLY,  0,   FALSE}, // {"*71;"," LADEPU-LAUFZEIT"," h     ", P&wwd[WW1].puwlh,					US_INT, 0, P&hid1,	V1, 0, 0},
		{P&PUWLEA[WW1],                                {JANEIN_FORMOP,   0},       NONE,  184,  1, READ_ONLY,  0,   FALSE}, // {"*72:"," LADEPUMPE EIN ?","       ", P&PUWLEA[WW1],		 JANEIN_FORMOP, 0, P&vis,		V1, 0, 0},
		{P&wwd[WW1].legio,                             {JANEIN_FORM,   0},         NONE,  185,  1, READ_ONLY,  0,   FALSE}, // {"*79:"," LEGIO.BETRIEB ?","       ", P&wwd[WW1].legio,		 JANEIN_FORM, 0, P&vis,		V1, 0, 0},
		{P&wws[WW1].Haut,                              {JANEIN_FORM,   0},         NONE,  186,  1, READ_ONLY,  0,   FALSE}, // {"*89:"," HANDBETRIEB ?  ","       ", P&wws[WW1].Haut,		 JANEIN_FORM, 0, P&vis,		E1, EREIGNIS, 0},
		{P&wws[WW1].Haut,                              {US_CHAR,   0},             NONE,  187,  1, READ_WRITE, 0,   FALSE}, // {" 99;"," HAND/AUTOMATIK "," HAND=1", P&wws[WW1].Haut,				 US_CHAR, 0, P&hid1,	V1, 0, 0},
		{P&wws[WW1].Lpea,                              {US_CHAR,   0},             NONE,  188,  1, READ_WRITE, 0,   FALSE}, // {" ->:"," LADEPU EIN/AUS "," EIN=1 ", P&wws[WW1].Lpea,				 US_CHAR, 0, P&hid1,	V1, 0, 0},
		{P&ort_idf,                                    {JANEIN_FORM,   0},         NONE,  189,  1, READ_ONLY,  0,   FALSE}, // {"*19;"," OBJ-ORT FEHLT ?","       ", P&ort_idf,									 JANEIN_FORM, 0, P&hid1,	E1, ANZEIGE, 0},
		{P&StationsAdr,                                {US_CHAR,   0},             NONE,  190,  1, READ_ONLY,  0,   FALSE}, // {"*20;"," STATION-ADRESSE","       ", P&StationsAdr,								 	 US_CHAR, 0, P&hid1,	V1, 0, 0},
		{P&Master_Idf,                                 {ASCII_FORM,  15},          NONE,  191,  8, READ_WRITE, 0,   FALSE}, // {"021;"," MASTER -IDF    ","       ", P&Master_Idf,								 TELE_FORM, 0, P&hid1,	V1, 0, 0},
		{P&Station_Idf,                                {ASCII_FORM,  15},          NONE,  199,  8, READ_WRITE, 0,   FALSE}, // {"022;"," STATION-IDF    ","       ", P&Station_Idf,								 TELE_FORM, 0, P&hid1,	V1, 0, 0},
		{P&Alarm_Idf[0],                               {ASCII_FORM,  15},          NONE,  207,  8, READ_WRITE, 0,   FALSE}, // {"023;"," ALARM-IDF 1    ","       ", P&Alarm_Idf[0],							 TELE_FORM, 0, P&hid1,	V1, 0, 0},
		{P&Alarm_Idf[1],                               {ASCII_FORM,  15},          NONE,  215,  8, READ_WRITE, 0,   FALSE}, // {"024;"," ALARM-IDF 2    ","       ", P&Alarm_Idf[1],							 TELE_FORM, 0, P&hid1,	V1, 0, 0},
		{P&Alarm_Idf[2],                               {ASCII_FORM,  15},          NONE,  223,  8, READ_WRITE, 0,   FALSE}, // {"025;"," ALARM-IDF 3    ","       ", P&Alarm_Idf[2],							 TELE_FORM, 0, P&hid1,	V1, 0, 0},
		{P&Service_Idf,                                {ASCII_FORM,  15},          NONE,  231,  8, READ_WRITE, 0,   FALSE}, // {"026;"," SERVICE-IDF    ","       ", P&Service_Idf,								 TELE_FORM, 0, P&hid1,	V1, 0, 0},
		{P&pin_fehlt,                                  {JANEIN_FORM,   0},         NONE,  239,  1, READ_ONLY,  0,   FALSE}, // {"*33;"," PIN FEHLT ?    ","       ", P&pin_fehlt,								 JANEIN_FORM, 0, P&hid1,	E1, ANZEIGE, 0},
		{P&mod37[0].error,                             {JANEIN_FORM,   0},         NONE,  240,  1, READ_ONLY,  0,   FALSE}, // {"*43;"," DAT-ERROR R37_1","       ", P&mod37[0].error,			 JANEIN_FORM, 0, P&r37vis[0],	E1, MODULE, 0},
		{P&mod38[0].error,                             {JANEIN_FORM,   0},         NONE,  241,  1, READ_ONLY,  0,   FALSE}, // {"*53;"," DAT-ERROR R38_1","       ", P&mod38[0].error,	 				 JANEIN_FORM, 0, P&r38vis[0],	E1, MODULE, 0},
		{P&mod39[0].error,                             {JANEIN_FORM,   0},         NONE,  242,  1, READ_ONLY,  0,   FALSE}, // {"*63;"," DAT-ERROR R39_1","       ", P&mod39[0].error,	 JANEIN_FORM,		0, P&r39vis[0],	E1, MODULE, 0},
		{P&mod39[0].Derror,                            {JANEIN_FORM,   0},         NONE,  243,  1, READ_ONLY,  0,   FALSE}, // {"*64;"," DIGI-ERR  R39_1","       ", P&mod39[0].Derror,	 JANEIN_FORM,   0, P&r39vis[0],	E1, MODULE, 0},
		{P&Resetcnt,                                   {US_INT,   0},              NONE,  244,  1, READ_ONLY,  0,   FALSE}, // {"*80;"," RESET COUNTER  ","       ", P&Resetcnt,							US_INT, 0, P&hid1,	V1, 0, 0},
		{P&rtc_error,                                  {JANEIN_FORM,   0},         NONE,  245,  1, READ_ONLY,  0,   FALSE}, // {"*82;"," RTC-UHR ERROR  ","       ", P&rtc_error,				 JANEIN_FORM, 0, P&hid1,	E1, EREIGNIS, 0},
		{P&noi_reanimate,                              {TASK_FORM,   0},           NONE,  246,  2, READ_ONLY,  0,   FALSE}, // {"*83;"," MAIN-CRASH:TASK","       ", P&noi_reanimate,			 TASK_FORM, 0, P&hid1,	E1, EREIGNIS, 0},
		{P&werks_sdm_code,                             {US_INT,   2},              NONE,  248,  1, READ_WRITE, 0,   FALSE}, // {" ->;"," SDM-ARCHIV-INIT","       ", P&werks_sdm_code,		  US_INT,  2, P&hid1,	V1, 0, 0},
		{P&reset_dae,                                  {S_INT,   1},               NONE,  249,  1, READ_WRITE, 0,   FALSE}, // {" ->;"," SDM-DAE-INIT   "," -DAE,E", P&reset_dae,			    	  S_INT, 1, P&hid1,	V1, 0, 0},
		{P&ferro_err,                                  {JANEIN_FORM,   0},         NONE,  250,  1, READ_ONLY,  0,   FALSE}, // {"*->;"," FerroRAM2 FEHLT","       ", P&ferro_err,			  JANEIN_FORM, 0, P&hid1,	E1, EREIGNIS, 0},
		{P&card_err,                                   {JANEIN_FORM,   0},         NONE,  251,  1, READ_ONLY,  0,   FALSE}, // {"*->;"," SDHC-Card FEHLT","       ", P&card_err,			  JANEIN_FORM, 0, P&hid1,	E1, EREIGNIS, 0},
		{P&Version_PTyp,                               {ASCII_FORM,  15},          NONE,  252,  8, READ_ONLY,  0,   FALSE}, // {"*96;"," PROGRAMM-TYP   ","       ", P&Version_PTyp, 			ASCII_FORM, 0, P&hid1,	V1, 0, 0},
		{P&Version_PVers,                              {DATE_FORM,   0},           NONE,  260,  2, READ_ONLY,  0,   FALSE}, // {"*97;"," PROGR.-VERSION ","       ", P&Version_PVers,			 DATE_FORM, 0, P&hid1,	V1, 0, 0},
		{P&Version_SVers,                              {DATE_FORM,   0},           NONE,  262,  2, READ_ONLY,  0,   FALSE}, // {"*98;"," SYSTEM-VERSION ","       ", P&Version_SVers, 		 DATE_FORM, 0, P&hid1,	V1, 0, 0},
	};
	const unsigned int modbusSlaveTableSize 	= (sizeof(modbusSlaveTable)/sizeof(modbusSlaveTableRow));
	modbusTableRowSlaveData modbusSlaveTableData[(sizeof(modbusSlaveTable)/sizeof(modbusSlaveTableRow))];
#else	// kein Slave definiert
	const modbusSlaveTableRow modbusSlaveTable[] = {
	};
	const unsigned int modbusSlaveTableSize 	= 0;
	modbusTableRowSlaveData modbusSlaveTableData[1];
#endif
#endif

