const Pgrup ze1[] = { // IN4
	{"_**:"," ZAEHLER IN4    ","       ", P&ZE[1],			 				ZE_FORMP, 1,	P&vis,	V1, 0, 0},
	{"*02:"," ZAEHLERWERT    ","       ", P&ZE[1],			 				ZE_FORMP, 0,	P&vis,	V1, 0, 0},
	{" 03;"," KOMMASTELLEN   ","       ", P&ZE[1],			 				ZE_FORMP, 2,	P&hid1,	V0, 0, 0},
	{" 04;"," DIMENSION      ","       ", P&ZE[1],			 				ZE_FORMP, 3,	P&hid1,	V0, 0, 0},
	{" 05;"," TEILERFAKTOR   ","       ", P&ZE[1],			 				ZE_FORMP, 4,	P&hid1,	V0, 0, 0},
	{" 06;"," IMPULSWERT     ","       ", P&ZE[1],							ZE_FORMP, 39,	P&hid1,	V0, 0, 0},
	{" ->;"," exponent       ","       ", P&ZE[1],							ZE_FORMP, 36,	P&hid2,	V0, 0, 0},
	{" 07;"," ZWISCHENZAEHLER","       ", P&ZE[1],							ZE_FORMP, 8,	P&hid1,	V0, 0, 0},
	{"*08;"," AKT.MON.VERBR. ","       ", P&ZE[1],			 				ZE_FORMP, 5,	P&hid1,	V0, 0, 0},
	{"*10:"," JANUAR         ","       ", P&ZE[1],			 				ZE_FORMP, 10, P&vis,	V1, 0, 0},
	{"*11:"," FEBRUAR        ","       ", P&ZE[1],			 				ZE_FORMP, 11, P&vis,	V1, 0, 0},
	{"*12:"," MAERZ          ","       ", P&ZE[1],			 				ZE_FORMP, 12, P&vis,	V1, 0, 0},
	{"*13:"," APRIL          ","       ", P&ZE[1],			 				ZE_FORMP, 13, P&vis,	V1, 0, 0},
	{"*14:"," MAI            ","       ", P&ZE[1],			 				ZE_FORMP, 14, P&vis,	V1, 0, 0},
	{"*15:"," JUNI           ","       ", P&ZE[1],			 				ZE_FORMP, 15, P&vis,	V1, 0, 0},
	{"*16:"," JULI           ","       ", P&ZE[1],			 				ZE_FORMP, 16, P&vis,	V1, 0, 0},
	{"*17:"," AUGUST         ","       ", P&ZE[1],			 				ZE_FORMP, 17, P&vis,	V1, 0, 0},
	{"*18:"," SEPTEMBER      ","       ", P&ZE[1],			 				ZE_FORMP, 18, P&vis,	V1, 0, 0},
	{"*19:"," OKTOBER        ","       ", P&ZE[1],			 				ZE_FORMP, 19, P&vis,	V1, 0, 0},
	{"*20:"," NOVEMBER       ","       ", P&ZE[1],			 				ZE_FORMP, 20, P&vis,	V1, 0, 0},
	{"*21:"," DEZEMBER       ","       ", P&ZE[1],			 				ZE_FORMP, 21, P&vis,	V1, 0, 0},
	{"*22:"," VORJAHR JANUAR ","       ", P&ZE[1],			 				ZE_FORMP, 22, P&vis,	V1, 0, 0},
	{"*23:"," VORJAHR FEBRUAR","       ", P&ZE[1],			 				ZE_FORMP, 23, P&vis,	V1, 0, 0},
	{"*24:"," VORJAHR MAERZ  ","       ", P&ZE[1],			 				ZE_FORMP, 24, P&vis,	V1, 0, 0},
	{"*25:"," VORJAHR APRIL  ","       ", P&ZE[1],			 				ZE_FORMP, 25, P&vis,	V1, 0, 0},
	{"*26:"," VORJAHR MAI    ","       ", P&ZE[1],			 				ZE_FORMP, 26, P&vis,	V1, 0, 0},
	{"*27:"," VORJAHR JUNI   ","       ", P&ZE[1],			 				ZE_FORMP, 27, P&vis,	V1, 0, 0},
	{"*28:"," VORJAHR JULI   ","       ", P&ZE[1],			 				ZE_FORMP, 28, P&vis,	V1, 0, 0},
	{"*29:"," VORJAHR AUGUST ","       ", P&ZE[1],			 				ZE_FORMP, 29, P&vis,	V1, 0, 0},
	{"*30:"," VORJAHR SEPT.  ","       ", P&ZE[1],			 				ZE_FORMP, 30, P&vis,	V1, 0, 0},
	{"*31:"," VORJAHR OKTOBER","       ", P&ZE[1],			 				ZE_FORMP, 31, P&vis,	V1, 0, 0},
	{"*32:"," VORJAHR NOVEMB.","       ", P&ZE[1],			 				ZE_FORMP, 32, P&vis,	V1, 0, 0},
	{"*33:"," VORJAHR DEZEMB.","       ", P&ZE[1],			 				ZE_FORMP, 33, P&vis,	V1, 0, 0},
	{" 34:"," SYNC.ZAEHLWERT ","       ", P&ZE[1],							ZE_FORMP, 6,  P&hid3,	V0, 0, 0},
	{" 35:"," SYNC.AKT.MONAT ","       ", P&ZE[1],							ZE_FORMP, 7,  P&hid3,	V0, 0, 0},
	{" 36:"," SYNC.MONAT 1-24","       ", P&ZE[1],							ZE_FORMP, 9,  P&hid3,	V0, 0, 0},
	{" 37:"," SYNC.MON.VERBR.","       ", P&ZE[1],							ZE_FORMP, 40, P&hid3,	V0, 0, 0},
	{" 38;"," ZAEHLERKONFIG. "," 8...1 ", P&ZE[1],							ZE_FORMP, 34,	P&hid1,	V0, 0, 0},
	{"*39;"," ZAEHLERMEDIUM  ","       ", P&ZE[1],							ZE_FORMP, 38,	P&hid1,	V0, 0, 0},
	{"*40;"," FEHLERSTATUS   "," 8...1 ", P&ZE[1],							ZE_FORMP, 35,	P&hid1,	V0, 0, 0},
	{"_41;"," ZAEHLERNUMMER  ","       ", P&ZE[1], 							ZE_FORMP, 41,	P&hid1,	V1, 0, 0},
	{"*42;"," STICHTAG       ","       ", P&ZE[1],							ZE_FORMP, 37,	P&hid1,	V0, 0, 0},
	{"*43;"," ZAEHLER VORJAHR","       ", P&ZE[1], 							ZE_FORMP, 42,	P&hid1,	V0, 0, 0},
	{" 44;"," SYNC.ZAEHL.VORJ","       ", P&ZE[1], 							ZE_FORMP, 43,	P&hid3,	V0, 0, 0},
};
